// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/chatbot/bot/okr/repository/okr.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pb "github.com/tsundata/assistant/api/pb"
)

// MockOkrRepository is a mock of OkrRepository interface.
type MockOkrRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOkrRepositoryMockRecorder
}

// MockOkrRepositoryMockRecorder is the mock recorder for MockOkrRepository.
type MockOkrRepositoryMockRecorder struct {
	mock *MockOkrRepository
}

// NewMockOkrRepository creates a new mock instance.
func NewMockOkrRepository(ctrl *gomock.Controller) *MockOkrRepository {
	mock := &MockOkrRepository{ctrl: ctrl}
	mock.recorder = &MockOkrRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOkrRepository) EXPECT() *MockOkrRepositoryMockRecorder {
	return m.recorder
}

// AggregateKeyResultValue mocks base method.
func (m *MockOkrRepository) AggregateKeyResultValue(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateKeyResultValue", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AggregateKeyResultValue indicates an expected call of AggregateKeyResultValue.
func (mr *MockOkrRepositoryMockRecorder) AggregateKeyResultValue(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateKeyResultValue", reflect.TypeOf((*MockOkrRepository)(nil).AggregateKeyResultValue), ctx, id)
}

// AggregateObjectiveValue mocks base method.
func (m *MockOkrRepository) AggregateObjectiveValue(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateObjectiveValue", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AggregateObjectiveValue indicates an expected call of AggregateObjectiveValue.
func (mr *MockOkrRepositoryMockRecorder) AggregateObjectiveValue(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateObjectiveValue", reflect.TypeOf((*MockOkrRepository)(nil).AggregateObjectiveValue), ctx, id)
}

// CreateKeyResult mocks base method.
func (m *MockOkrRepository) CreateKeyResult(ctx context.Context, keyResult *pb.KeyResult) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyResult", ctx, keyResult)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyResult indicates an expected call of CreateKeyResult.
func (mr *MockOkrRepositoryMockRecorder) CreateKeyResult(ctx, keyResult interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyResult", reflect.TypeOf((*MockOkrRepository)(nil).CreateKeyResult), ctx, keyResult)
}

// CreateKeyResultValue mocks base method.
func (m *MockOkrRepository) CreateKeyResultValue(ctx context.Context, keyResultValue *pb.KeyResultValue) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyResultValue", ctx, keyResultValue)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyResultValue indicates an expected call of CreateKeyResultValue.
func (mr *MockOkrRepositoryMockRecorder) CreateKeyResultValue(ctx, keyResultValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyResultValue", reflect.TypeOf((*MockOkrRepository)(nil).CreateKeyResultValue), ctx, keyResultValue)
}

// CreateObjective mocks base method.
func (m *MockOkrRepository) CreateObjective(ctx context.Context, objective *pb.Objective) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjective", ctx, objective)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjective indicates an expected call of CreateObjective.
func (mr *MockOkrRepositoryMockRecorder) CreateObjective(ctx, objective interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjective", reflect.TypeOf((*MockOkrRepository)(nil).CreateObjective), ctx, objective)
}

// DeleteKeyResult mocks base method.
func (m *MockOkrRepository) DeleteKeyResult(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyResult", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeyResult indicates an expected call of DeleteKeyResult.
func (mr *MockOkrRepositoryMockRecorder) DeleteKeyResult(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyResult", reflect.TypeOf((*MockOkrRepository)(nil).DeleteKeyResult), ctx, id)
}

// DeleteKeyResultBySequence mocks base method.
func (m *MockOkrRepository) DeleteKeyResultBySequence(ctx context.Context, userId, sequence int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyResultBySequence", ctx, userId, sequence)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeyResultBySequence indicates an expected call of DeleteKeyResultBySequence.
func (mr *MockOkrRepositoryMockRecorder) DeleteKeyResultBySequence(ctx, userId, sequence interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyResultBySequence", reflect.TypeOf((*MockOkrRepository)(nil).DeleteKeyResultBySequence), ctx, userId, sequence)
}

// DeleteObjective mocks base method.
func (m *MockOkrRepository) DeleteObjective(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjective", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjective indicates an expected call of DeleteObjective.
func (mr *MockOkrRepositoryMockRecorder) DeleteObjective(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjective", reflect.TypeOf((*MockOkrRepository)(nil).DeleteObjective), ctx, id)
}

// DeleteObjectiveBySequence mocks base method.
func (m *MockOkrRepository) DeleteObjectiveBySequence(ctx context.Context, userId, sequence int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectiveBySequence", ctx, userId, sequence)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectiveBySequence indicates an expected call of DeleteObjectiveBySequence.
func (mr *MockOkrRepositoryMockRecorder) DeleteObjectiveBySequence(ctx, userId, sequence interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectiveBySequence", reflect.TypeOf((*MockOkrRepository)(nil).DeleteObjectiveBySequence), ctx, userId, sequence)
}

// GetKeyResultByID mocks base method.
func (m *MockOkrRepository) GetKeyResultByID(ctx context.Context, id int64) (*pb.KeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyResultByID", ctx, id)
	ret0, _ := ret[0].(*pb.KeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyResultByID indicates an expected call of GetKeyResultByID.
func (mr *MockOkrRepositoryMockRecorder) GetKeyResultByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyResultByID", reflect.TypeOf((*MockOkrRepository)(nil).GetKeyResultByID), ctx, id)
}

// GetKeyResultBySequence mocks base method.
func (m *MockOkrRepository) GetKeyResultBySequence(ctx context.Context, userId, sequence int64) (*pb.KeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyResultBySequence", ctx, userId, sequence)
	ret0, _ := ret[0].(*pb.KeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyResultBySequence indicates an expected call of GetKeyResultBySequence.
func (mr *MockOkrRepositoryMockRecorder) GetKeyResultBySequence(ctx, userId, sequence interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyResultBySequence", reflect.TypeOf((*MockOkrRepository)(nil).GetKeyResultBySequence), ctx, userId, sequence)
}

// GetKeyResultValues mocks base method.
func (m *MockOkrRepository) GetKeyResultValues(ctx context.Context, keyResultId int64) ([]*pb.KeyResultValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyResultValues", ctx, keyResultId)
	ret0, _ := ret[0].([]*pb.KeyResultValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyResultValues indicates an expected call of GetKeyResultValues.
func (mr *MockOkrRepositoryMockRecorder) GetKeyResultValues(ctx, keyResultId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyResultValues", reflect.TypeOf((*MockOkrRepository)(nil).GetKeyResultValues), ctx, keyResultId)
}

// GetObjectiveByID mocks base method.
func (m *MockOkrRepository) GetObjectiveByID(ctx context.Context, id int64) (*pb.Objective, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectiveByID", ctx, id)
	ret0, _ := ret[0].(*pb.Objective)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectiveByID indicates an expected call of GetObjectiveByID.
func (mr *MockOkrRepositoryMockRecorder) GetObjectiveByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectiveByID", reflect.TypeOf((*MockOkrRepository)(nil).GetObjectiveByID), ctx, id)
}

// GetObjectiveBySequence mocks base method.
func (m *MockOkrRepository) GetObjectiveBySequence(ctx context.Context, userId, sequence int64) (*pb.Objective, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectiveBySequence", ctx, userId, sequence)
	ret0, _ := ret[0].(*pb.Objective)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectiveBySequence indicates an expected call of GetObjectiveBySequence.
func (mr *MockOkrRepositoryMockRecorder) GetObjectiveBySequence(ctx, userId, sequence interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectiveBySequence", reflect.TypeOf((*MockOkrRepository)(nil).GetObjectiveBySequence), ctx, userId, sequence)
}

// ListKeyResults mocks base method.
func (m *MockOkrRepository) ListKeyResults(ctx context.Context, userId int64) ([]*pb.KeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeyResults", ctx, userId)
	ret0, _ := ret[0].([]*pb.KeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeyResults indicates an expected call of ListKeyResults.
func (mr *MockOkrRepositoryMockRecorder) ListKeyResults(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeyResults", reflect.TypeOf((*MockOkrRepository)(nil).ListKeyResults), ctx, userId)
}

// ListKeyResultsById mocks base method.
func (m *MockOkrRepository) ListKeyResultsById(ctx context.Context, id []int64) ([]*pb.KeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeyResultsById", ctx, id)
	ret0, _ := ret[0].([]*pb.KeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeyResultsById indicates an expected call of ListKeyResultsById.
func (mr *MockOkrRepositoryMockRecorder) ListKeyResultsById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeyResultsById", reflect.TypeOf((*MockOkrRepository)(nil).ListKeyResultsById), ctx, id)
}

// ListKeyResultsByObjectiveId mocks base method.
func (m *MockOkrRepository) ListKeyResultsByObjectiveId(ctx context.Context, objectiveId int64) ([]*pb.KeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeyResultsByObjectiveId", ctx, objectiveId)
	ret0, _ := ret[0].([]*pb.KeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeyResultsByObjectiveId indicates an expected call of ListKeyResultsByObjectiveId.
func (mr *MockOkrRepositoryMockRecorder) ListKeyResultsByObjectiveId(ctx, objectiveId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeyResultsByObjectiveId", reflect.TypeOf((*MockOkrRepository)(nil).ListKeyResultsByObjectiveId), ctx, objectiveId)
}

// ListObjectives mocks base method.
func (m *MockOkrRepository) ListObjectives(ctx context.Context, userId int64) ([]*pb.Objective, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectives", ctx, userId)
	ret0, _ := ret[0].([]*pb.Objective)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectives indicates an expected call of ListObjectives.
func (mr *MockOkrRepositoryMockRecorder) ListObjectives(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectives", reflect.TypeOf((*MockOkrRepository)(nil).ListObjectives), ctx, userId)
}

// UpdateKeyResult mocks base method.
func (m *MockOkrRepository) UpdateKeyResult(ctx context.Context, keyResult *pb.KeyResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeyResult", ctx, keyResult)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKeyResult indicates an expected call of UpdateKeyResult.
func (mr *MockOkrRepositoryMockRecorder) UpdateKeyResult(ctx, keyResult interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyResult", reflect.TypeOf((*MockOkrRepository)(nil).UpdateKeyResult), ctx, keyResult)
}

// UpdateObjective mocks base method.
func (m *MockOkrRepository) UpdateObjective(ctx context.Context, objective *pb.Objective) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateObjective", ctx, objective)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateObjective indicates an expected call of UpdateObjective.
func (mr *MockOkrRepositoryMockRecorder) UpdateObjective(ctx, objective interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateObjective", reflect.TypeOf((*MockOkrRepository)(nil).UpdateObjective), ctx, objective)
}
