# the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0

builds:
  # app
  - main: ./cmd/server
    id: "server"
    binary: "server"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^test:'
      - '^merge:'
      - '^Merge pull request'
      - '^Merge branch'
      - '^debug:'
      - '^ci:'

env_files:
  github_token: ~/.gh_token

release:
  github:
    owner: tsundata
    name: assistant
  name_template: "{{.Tag}}"
