// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	pb "github.com/tsundata/assistant/api/pb"
)

// MessageServer is an autogenerated mock type for the MessageServer type
type MessageServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) Create(_a0 context.Context, _a1 *pb.MessageRequest) (*pb.TextsReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.TextsReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.MessageRequest) *pb.TextsReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TextsReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.MessageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateActionMessage provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) CreateActionMessage(_a0 context.Context, _a1 *pb.TextRequest) (*pb.StateReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.StateReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TextRequest) *pb.StateReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.StateReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.TextRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) Delete(_a0 context.Context, _a1 *pb.MessageRequest) (*pb.TextReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.TextReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.MessageRequest) *pb.TextReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TextReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.MessageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWorkflowMessage provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) DeleteWorkflowMessage(_a0 context.Context, _a1 *pb.MessageRequest) (*pb.StateReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.StateReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.MessageRequest) *pb.StateReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.StateReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.MessageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) Get(_a0 context.Context, _a1 *pb.MessageRequest) (*pb.MessageReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.MessageReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.MessageRequest) *pb.MessageReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.MessageReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.MessageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActionMessages provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) GetActionMessages(_a0 context.Context, _a1 *pb.TextRequest) (*pb.ActionReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.ActionReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TextRequest) *pb.ActionReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ActionReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.TextRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) List(_a0 context.Context, _a1 *pb.MessageRequest) (*pb.MessageListReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.MessageListReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.MessageRequest) *pb.MessageListReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.MessageListReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.MessageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) Run(_a0 context.Context, _a1 *pb.MessageRequest) (*pb.TextReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.TextReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.MessageRequest) *pb.TextReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TextReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.MessageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Send provides a mock function with given fields: _a0, _a1
func (_m *MessageServer) Send(_a0 context.Context, _a1 *pb.MessageRequest) (*pb.StateReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.StateReply
	if rf, ok := ret.Get(0).(func(context.Context, *pb.MessageRequest) *pb.StateReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.StateReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.MessageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
