version: '3'

services:

  server:
    image: ghcr.io/tsundata/assistant:${APP_VERSION}
    restart: always
    environment:
      ETCD_ADDRESS: ${ETCD_ADDRESS}
      ETCD_USERNAME: ${ETCD_USERNAME}
      ETCD_PASSWORD: ${ETCD_PASSWORD}
    ports:
      - "5000:5000"
