version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./tmp/redis/data:/data
      - ../../configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  influx:
    image: quay.io/influxdb/influxdb:v2.0.3
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=12345678
    volumes:
      - ../../configs/influx/influx.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"

  jaeger-collector:
    image: jaegertracing/all-in-one:1.22
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: db
      MYSQL_PASSWORD: 123456
    volumes:
      - ./tmp/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  etcd:
    image: bitnami/etcd:3.5.0
    environment:
     - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
     - ./tmp/etcd/data:/bitnami/etcd
    ports:
     - "2379:2379"
     - "2380:2380"
