// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chatbot.proto

package pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChatbotRequest struct {
	MessageId   int64  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageUuid string `protobuf:"bytes,2,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
}

func (m *ChatbotRequest) Reset()         { *m = ChatbotRequest{} }
func (m *ChatbotRequest) String() string { return proto.CompactTextString(m) }
func (*ChatbotRequest) ProtoMessage()    {}
func (*ChatbotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{0}
}
func (m *ChatbotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatbotRequest.Unmarshal(m, b)
}
func (m *ChatbotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatbotRequest.Marshal(b, m, deterministic)
}
func (m *ChatbotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatbotRequest.Merge(m, src)
}
func (m *ChatbotRequest) XXX_Size() int {
	return xxx_messageInfo_ChatbotRequest.Size(m)
}
func (m *ChatbotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatbotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChatbotRequest proto.InternalMessageInfo

func (m *ChatbotRequest) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *ChatbotRequest) GetMessageUuid() string {
	if m != nil {
		return m.MessageUuid
	}
	return ""
}

type ChatbotReply struct {
	State bool `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *ChatbotReply) Reset()         { *m = ChatbotReply{} }
func (m *ChatbotReply) String() string { return proto.CompactTextString(m) }
func (*ChatbotReply) ProtoMessage()    {}
func (*ChatbotReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{1}
}
func (m *ChatbotReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatbotReply.Unmarshal(m, b)
}
func (m *ChatbotReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatbotReply.Marshal(b, m, deterministic)
}
func (m *ChatbotReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatbotReply.Merge(m, src)
}
func (m *ChatbotReply) XXX_Size() int {
	return xxx_messageInfo_ChatbotReply.Size(m)
}
func (m *ChatbotReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatbotReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChatbotReply proto.InternalMessageInfo

func (m *ChatbotReply) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

type GroupBotRequest struct {
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Bot     *Bot  `protobuf:"bytes,2,opt,name=bot,proto3" json:"bot,omitempty"`
}

func (m *GroupBotRequest) Reset()         { *m = GroupBotRequest{} }
func (m *GroupBotRequest) String() string { return proto.CompactTextString(m) }
func (*GroupBotRequest) ProtoMessage()    {}
func (*GroupBotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{2}
}
func (m *GroupBotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupBotRequest.Unmarshal(m, b)
}
func (m *GroupBotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupBotRequest.Marshal(b, m, deterministic)
}
func (m *GroupBotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupBotRequest.Merge(m, src)
}
func (m *GroupBotRequest) XXX_Size() int {
	return xxx_messageInfo_GroupBotRequest.Size(m)
}
func (m *GroupBotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupBotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupBotRequest proto.InternalMessageInfo

func (m *GroupBotRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupBotRequest) GetBot() *Bot {
	if m != nil {
		return m.Bot
	}
	return nil
}

type BotSettingRequest struct {
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// @inject_tag: query:"group_uuid"
	GroupUuid string `protobuf:"bytes,2,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty" query:"group_uuid"`
	BotId     int64  `protobuf:"varint,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// @inject_tag: query:"bot_uuid"
	BotUuid string `protobuf:"bytes,4,opt,name=bot_uuid,json=botUuid,proto3" json:"bot_uuid,omitempty" query:"bot_uuid"`
	Kvs     []*KV  `protobuf:"bytes,5,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (m *BotSettingRequest) Reset()         { *m = BotSettingRequest{} }
func (m *BotSettingRequest) String() string { return proto.CompactTextString(m) }
func (*BotSettingRequest) ProtoMessage()    {}
func (*BotSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{3}
}
func (m *BotSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotSettingRequest.Unmarshal(m, b)
}
func (m *BotSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotSettingRequest.Marshal(b, m, deterministic)
}
func (m *BotSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotSettingRequest.Merge(m, src)
}
func (m *BotSettingRequest) XXX_Size() int {
	return xxx_messageInfo_BotSettingRequest.Size(m)
}
func (m *BotSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotSettingRequest proto.InternalMessageInfo

func (m *BotSettingRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *BotSettingRequest) GetGroupUuid() string {
	if m != nil {
		return m.GroupUuid
	}
	return ""
}

func (m *BotSettingRequest) GetBotId() int64 {
	if m != nil {
		return m.BotId
	}
	return 0
}

func (m *BotSettingRequest) GetBotUuid() string {
	if m != nil {
		return m.BotUuid
	}
	return ""
}

func (m *BotSettingRequest) GetKvs() []*KV {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type BotSettingReply struct {
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	BotId   int64 `protobuf:"varint,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Kvs     []*KV `protobuf:"bytes,3,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (m *BotSettingReply) Reset()         { *m = BotSettingReply{} }
func (m *BotSettingReply) String() string { return proto.CompactTextString(m) }
func (*BotSettingReply) ProtoMessage()    {}
func (*BotSettingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{4}
}
func (m *BotSettingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotSettingReply.Unmarshal(m, b)
}
func (m *BotSettingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotSettingReply.Marshal(b, m, deterministic)
}
func (m *BotSettingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotSettingReply.Merge(m, src)
}
func (m *BotSettingReply) XXX_Size() int {
	return xxx_messageInfo_BotSettingReply.Size(m)
}
func (m *BotSettingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BotSettingReply.DiscardUnknown(m)
}

var xxx_messageInfo_BotSettingReply proto.InternalMessageInfo

func (m *BotSettingReply) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *BotSettingReply) GetBotId() int64 {
	if m != nil {
		return m.BotId
	}
	return 0
}

func (m *BotSettingReply) GetKvs() []*KV {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type GroupSettingRequest struct {
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// @inject_tag: query:"group_uuid"
	GroupUuid string `protobuf:"bytes,2,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty" query:"group_uuid"`
	Kvs       []*KV  `protobuf:"bytes,3,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (m *GroupSettingRequest) Reset()         { *m = GroupSettingRequest{} }
func (m *GroupSettingRequest) String() string { return proto.CompactTextString(m) }
func (*GroupSettingRequest) ProtoMessage()    {}
func (*GroupSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{5}
}
func (m *GroupSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupSettingRequest.Unmarshal(m, b)
}
func (m *GroupSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupSettingRequest.Marshal(b, m, deterministic)
}
func (m *GroupSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSettingRequest.Merge(m, src)
}
func (m *GroupSettingRequest) XXX_Size() int {
	return xxx_messageInfo_GroupSettingRequest.Size(m)
}
func (m *GroupSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSettingRequest proto.InternalMessageInfo

func (m *GroupSettingRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupSettingRequest) GetGroupUuid() string {
	if m != nil {
		return m.GroupUuid
	}
	return ""
}

func (m *GroupSettingRequest) GetKvs() []*KV {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type GroupSettingReply struct {
	GroupId   int64  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupUuid string `protobuf:"bytes,2,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty"`
	Kvs       []*KV  `protobuf:"bytes,3,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (m *GroupSettingReply) Reset()         { *m = GroupSettingReply{} }
func (m *GroupSettingReply) String() string { return proto.CompactTextString(m) }
func (*GroupSettingReply) ProtoMessage()    {}
func (*GroupSettingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{6}
}
func (m *GroupSettingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupSettingReply.Unmarshal(m, b)
}
func (m *GroupSettingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupSettingReply.Marshal(b, m, deterministic)
}
func (m *GroupSettingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSettingReply.Merge(m, src)
}
func (m *GroupSettingReply) XXX_Size() int {
	return xxx_messageInfo_GroupSettingReply.Size(m)
}
func (m *GroupSettingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSettingReply.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSettingReply proto.InternalMessageInfo

func (m *GroupSettingReply) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupSettingReply) GetGroupUuid() string {
	if m != nil {
		return m.GroupUuid
	}
	return ""
}

func (m *GroupSettingReply) GetKvs() []*KV {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type Group struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"sequence"
	Sequence int64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty" db:"sequence"`
	// @inject_tag: db:"type"
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty" db:"type"`
	// @inject_tag: db:"uuid"
	Uuid string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty" db:"uuid"`
	// @inject_tag: db:"user_id"
	UserId int64 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" db:"user_id"`
	// @inject_tag: db:"name"
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty" db:"name"`
	// @inject_tag: db:"avatar"
	Avatar string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty" db:"avatar"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{7}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Group) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Group) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Group) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Group) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Group) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GroupBot struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"group_id"
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id"`
	// @inject_tag: db:"bot_id"
	BotId int64 `protobuf:"varint,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty" db:"bot_id"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *GroupBot) Reset()         { *m = GroupBot{} }
func (m *GroupBot) String() string { return proto.CompactTextString(m) }
func (*GroupBot) ProtoMessage()    {}
func (*GroupBot) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{8}
}
func (m *GroupBot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupBot.Unmarshal(m, b)
}
func (m *GroupBot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupBot.Marshal(b, m, deterministic)
}
func (m *GroupBot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupBot.Merge(m, src)
}
func (m *GroupBot) XXX_Size() int {
	return xxx_messageInfo_GroupBot.Size(m)
}
func (m *GroupBot) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupBot.DiscardUnknown(m)
}

var xxx_messageInfo_GroupBot proto.InternalMessageInfo

func (m *GroupBot) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupBot) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupBot) GetBotId() int64 {
	if m != nil {
		return m.BotId
	}
	return 0
}

func (m *GroupBot) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GroupBot) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GroupBotSetting struct {
	// @inject_tag: db:"group_id"
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id"`
	// @inject_tag: db:"bot_id"
	BotId int64 `protobuf:"varint,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty" db:"bot_id"`
	// @inject_tag: db:"key"
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty" db:"key"`
	// @inject_tag: db:"value"
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty" db:"value"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *GroupBotSetting) Reset()         { *m = GroupBotSetting{} }
func (m *GroupBotSetting) String() string { return proto.CompactTextString(m) }
func (*GroupBotSetting) ProtoMessage()    {}
func (*GroupBotSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{9}
}
func (m *GroupBotSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupBotSetting.Unmarshal(m, b)
}
func (m *GroupBotSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupBotSetting.Marshal(b, m, deterministic)
}
func (m *GroupBotSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupBotSetting.Merge(m, src)
}
func (m *GroupBotSetting) XXX_Size() int {
	return xxx_messageInfo_GroupBotSetting.Size(m)
}
func (m *GroupBotSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupBotSetting.DiscardUnknown(m)
}

var xxx_messageInfo_GroupBotSetting proto.InternalMessageInfo

func (m *GroupBotSetting) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupBotSetting) GetBotId() int64 {
	if m != nil {
		return m.BotId
	}
	return 0
}

func (m *GroupBotSetting) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GroupBotSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GroupBotSetting) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GroupBotSetting) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GroupSetting struct {
	// @inject_tag: db:"group_id"
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id"`
	// @inject_tag: db:"key"
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" db:"key"`
	// @inject_tag: db:"value"
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" db:"value"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *GroupSetting) Reset()         { *m = GroupSetting{} }
func (m *GroupSetting) String() string { return proto.CompactTextString(m) }
func (*GroupSetting) ProtoMessage()    {}
func (*GroupSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{10}
}
func (m *GroupSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupSetting.Unmarshal(m, b)
}
func (m *GroupSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupSetting.Marshal(b, m, deterministic)
}
func (m *GroupSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSetting.Merge(m, src)
}
func (m *GroupSetting) XXX_Size() int {
	return xxx_messageInfo_GroupSetting.Size(m)
}
func (m *GroupSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSetting.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSetting proto.InternalMessageInfo

func (m *GroupSetting) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupSetting) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GroupSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GroupSetting) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GroupSetting) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GroupTag struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"group_id"
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id"`
	// @inject_tag: db:"tag"
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty" db:"tag"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *GroupTag) Reset()         { *m = GroupTag{} }
func (m *GroupTag) String() string { return proto.CompactTextString(m) }
func (*GroupTag) ProtoMessage()    {}
func (*GroupTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{11}
}
func (m *GroupTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTag.Unmarshal(m, b)
}
func (m *GroupTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTag.Marshal(b, m, deterministic)
}
func (m *GroupTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTag.Merge(m, src)
}
func (m *GroupTag) XXX_Size() int {
	return xxx_messageInfo_GroupTag.Size(m)
}
func (m *GroupTag) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTag.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTag proto.InternalMessageInfo

func (m *GroupTag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupTag) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupTag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GroupTag) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GroupTag) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Bot struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"uuid"
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty" db:"uuid"`
	// @inject_tag: db:"name"
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" db:"name"`
	// @inject_tag: db:"identifier"
	Identifier string `protobuf:"bytes,5,opt,name=identifier,proto3" json:"identifier,omitempty" db:"identifier"`
	// @inject_tag: db:"detail"
	Detail string `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty" db:"detail"`
	// @inject_tag: db:"avatar"
	Avatar string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty" db:"avatar"`
	// @inject_tag: db:"extend"
	Extend string `protobuf:"bytes,8,opt,name=extend,proto3" json:"extend,omitempty" db:"extend"`
	// @inject_tag: db:"status"
	Status int32 `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty" db:"status"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
	// @inject_tag: db:"group_id" gorm:"->"
	GroupId int64 `protobuf:"varint,12,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id" gorm:"->"`
}

func (m *Bot) Reset()         { *m = Bot{} }
func (m *Bot) String() string { return proto.CompactTextString(m) }
func (*Bot) ProtoMessage()    {}
func (*Bot) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{12}
}
func (m *Bot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bot.Unmarshal(m, b)
}
func (m *Bot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bot.Marshal(b, m, deterministic)
}
func (m *Bot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bot.Merge(m, src)
}
func (m *Bot) XXX_Size() int {
	return xxx_messageInfo_Bot.Size(m)
}
func (m *Bot) XXX_DiscardUnknown() {
	xxx_messageInfo_Bot.DiscardUnknown(m)
}

var xxx_messageInfo_Bot proto.InternalMessageInfo

func (m *Bot) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bot) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Bot) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bot) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Bot) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Bot) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Bot) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func (m *Bot) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Bot) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Bot) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Bot) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type BotRequest struct {
	Bot *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	// @inject_tag: query:"group_uuid"
	GroupUuid string `protobuf:"bytes,2,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty" query:"group_uuid"`
	// @inject_tag: query:"bot_uuid"
	BotUuid string `protobuf:"bytes,3,opt,name=bot_uuid,json=botUuid,proto3" json:"bot_uuid,omitempty" query:"bot_uuid"`
}

func (m *BotRequest) Reset()         { *m = BotRequest{} }
func (m *BotRequest) String() string { return proto.CompactTextString(m) }
func (*BotRequest) ProtoMessage()    {}
func (*BotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{13}
}
func (m *BotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotRequest.Unmarshal(m, b)
}
func (m *BotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotRequest.Marshal(b, m, deterministic)
}
func (m *BotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotRequest.Merge(m, src)
}
func (m *BotRequest) XXX_Size() int {
	return xxx_messageInfo_BotRequest.Size(m)
}
func (m *BotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotRequest proto.InternalMessageInfo

func (m *BotRequest) GetBot() *Bot {
	if m != nil {
		return m.Bot
	}
	return nil
}

func (m *BotRequest) GetGroupUuid() string {
	if m != nil {
		return m.GroupUuid
	}
	return ""
}

func (m *BotRequest) GetBotUuid() string {
	if m != nil {
		return m.BotUuid
	}
	return ""
}

type BotReply struct {
	Bot *Bot `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
}

func (m *BotReply) Reset()         { *m = BotReply{} }
func (m *BotReply) String() string { return proto.CompactTextString(m) }
func (*BotReply) ProtoMessage()    {}
func (*BotReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{14}
}
func (m *BotReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotReply.Unmarshal(m, b)
}
func (m *BotReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotReply.Marshal(b, m, deterministic)
}
func (m *BotReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotReply.Merge(m, src)
}
func (m *BotReply) XXX_Size() int {
	return xxx_messageInfo_BotReply.Size(m)
}
func (m *BotReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BotReply.DiscardUnknown(m)
}

var xxx_messageInfo_BotReply proto.InternalMessageInfo

func (m *BotReply) GetBot() *Bot {
	if m != nil {
		return m.Bot
	}
	return nil
}

type BotsRequest struct {
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// @inject_tag: query:"group_uuid"
	GroupUuid string `protobuf:"bytes,2,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty" query:"group_uuid"`
}

func (m *BotsRequest) Reset()         { *m = BotsRequest{} }
func (m *BotsRequest) String() string { return proto.CompactTextString(m) }
func (*BotsRequest) ProtoMessage()    {}
func (*BotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{15}
}
func (m *BotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotsRequest.Unmarshal(m, b)
}
func (m *BotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotsRequest.Marshal(b, m, deterministic)
}
func (m *BotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotsRequest.Merge(m, src)
}
func (m *BotsRequest) XXX_Size() int {
	return xxx_messageInfo_BotsRequest.Size(m)
}
func (m *BotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotsRequest proto.InternalMessageInfo

func (m *BotsRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *BotsRequest) GetGroupUuid() string {
	if m != nil {
		return m.GroupUuid
	}
	return ""
}

type BotsReply struct {
	Bots []*Bot `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
}

func (m *BotsReply) Reset()         { *m = BotsReply{} }
func (m *BotsReply) String() string { return proto.CompactTextString(m) }
func (*BotsReply) ProtoMessage()    {}
func (*BotsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{16}
}
func (m *BotsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotsReply.Unmarshal(m, b)
}
func (m *BotsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotsReply.Marshal(b, m, deterministic)
}
func (m *BotsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotsReply.Merge(m, src)
}
func (m *BotsReply) XXX_Size() int {
	return xxx_messageInfo_BotsReply.Size(m)
}
func (m *BotsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BotsReply.DiscardUnknown(m)
}

var xxx_messageInfo_BotsReply proto.InternalMessageInfo

func (m *BotsReply) GetBots() []*Bot {
	if m != nil {
		return m.Bots
	}
	return nil
}

type GroupRequest struct {
	Group *Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (m *GroupRequest) Reset()         { *m = GroupRequest{} }
func (m *GroupRequest) String() string { return proto.CompactTextString(m) }
func (*GroupRequest) ProtoMessage()    {}
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{17}
}
func (m *GroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupRequest.Unmarshal(m, b)
}
func (m *GroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupRequest.Marshal(b, m, deterministic)
}
func (m *GroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupRequest.Merge(m, src)
}
func (m *GroupRequest) XXX_Size() int {
	return xxx_messageInfo_GroupRequest.Size(m)
}
func (m *GroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupRequest proto.InternalMessageInfo

func (m *GroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupReply struct {
	Group *Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (m *GroupReply) Reset()         { *m = GroupReply{} }
func (m *GroupReply) String() string { return proto.CompactTextString(m) }
func (*GroupReply) ProtoMessage()    {}
func (*GroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{18}
}
func (m *GroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupReply.Unmarshal(m, b)
}
func (m *GroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupReply.Marshal(b, m, deterministic)
}
func (m *GroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupReply.Merge(m, src)
}
func (m *GroupReply) XXX_Size() int {
	return xxx_messageInfo_GroupReply.Size(m)
}
func (m *GroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_GroupReply proto.InternalMessageInfo

func (m *GroupReply) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupItem struct {
	Sequence    int64        `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Type        int32        `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Uuid        string       `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name        string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Avatar      string       `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	UnreadCount int32        `protobuf:"varint,7,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	LastMessage *LastMessage `protobuf:"bytes,8,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	BotAvatar   []string     `protobuf:"bytes,9,rep,name=bot_avatar,json=botAvatar,proto3" json:"bot_avatar,omitempty"`
	Id          int64        `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *GroupItem) Reset()         { *m = GroupItem{} }
func (m *GroupItem) String() string { return proto.CompactTextString(m) }
func (*GroupItem) ProtoMessage()    {}
func (*GroupItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{19}
}
func (m *GroupItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupItem.Unmarshal(m, b)
}
func (m *GroupItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupItem.Marshal(b, m, deterministic)
}
func (m *GroupItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupItem.Merge(m, src)
}
func (m *GroupItem) XXX_Size() int {
	return xxx_messageInfo_GroupItem.Size(m)
}
func (m *GroupItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupItem.DiscardUnknown(m)
}

var xxx_messageInfo_GroupItem proto.InternalMessageInfo

func (m *GroupItem) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *GroupItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GroupItem) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GroupItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupItem) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GroupItem) GetUnreadCount() int32 {
	if m != nil {
		return m.UnreadCount
	}
	return 0
}

func (m *GroupItem) GetLastMessage() *LastMessage {
	if m != nil {
		return m.LastMessage
	}
	return nil
}

func (m *GroupItem) GetBotAvatar() []string {
	if m != nil {
		return m.BotAvatar
	}
	return nil
}

func (m *GroupItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LastMessage struct {
	LastSender string `protobuf:"bytes,1,opt,name=last_sender,json=lastSender,proto3" json:"last_sender,omitempty"`
	Content    string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *LastMessage) Reset()         { *m = LastMessage{} }
func (m *LastMessage) String() string { return proto.CompactTextString(m) }
func (*LastMessage) ProtoMessage()    {}
func (*LastMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{20}
}
func (m *LastMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastMessage.Unmarshal(m, b)
}
func (m *LastMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastMessage.Marshal(b, m, deterministic)
}
func (m *LastMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastMessage.Merge(m, src)
}
func (m *LastMessage) XXX_Size() int {
	return xxx_messageInfo_LastMessage.Size(m)
}
func (m *LastMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LastMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LastMessage proto.InternalMessageInfo

func (m *LastMessage) GetLastSender() string {
	if m != nil {
		return m.LastSender
	}
	return ""
}

func (m *LastMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GetGroupsReply struct {
	Groups []*GroupItem `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (m *GetGroupsReply) Reset()         { *m = GetGroupsReply{} }
func (m *GetGroupsReply) String() string { return proto.CompactTextString(m) }
func (*GetGroupsReply) ProtoMessage()    {}
func (*GetGroupsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{21}
}
func (m *GetGroupsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupsReply.Unmarshal(m, b)
}
func (m *GetGroupsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupsReply.Marshal(b, m, deterministic)
}
func (m *GetGroupsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupsReply.Merge(m, src)
}
func (m *GetGroupsReply) XXX_Size() int {
	return xxx_messageInfo_GetGroupsReply.Size(m)
}
func (m *GetGroupsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupsReply proto.InternalMessageInfo

func (m *GetGroupsReply) GetGroups() []*GroupItem {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GetGroupReply struct {
	Group *GroupItem `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (m *GetGroupReply) Reset()         { *m = GetGroupReply{} }
func (m *GetGroupReply) String() string { return proto.CompactTextString(m) }
func (*GetGroupReply) ProtoMessage()    {}
func (*GetGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc44097314201ac, []int{22}
}
func (m *GetGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupReply.Unmarshal(m, b)
}
func (m *GetGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupReply.Marshal(b, m, deterministic)
}
func (m *GetGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupReply.Merge(m, src)
}
func (m *GetGroupReply) XXX_Size() int {
	return xxx_messageInfo_GetGroupReply.Size(m)
}
func (m *GetGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupReply proto.InternalMessageInfo

func (m *GetGroupReply) GetGroup() *GroupItem {
	if m != nil {
		return m.Group
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatbotRequest)(nil), "pb.ChatbotRequest")
	proto.RegisterType((*ChatbotReply)(nil), "pb.ChatbotReply")
	proto.RegisterType((*GroupBotRequest)(nil), "pb.GroupBotRequest")
	proto.RegisterType((*BotSettingRequest)(nil), "pb.BotSettingRequest")
	proto.RegisterType((*BotSettingReply)(nil), "pb.BotSettingReply")
	proto.RegisterType((*GroupSettingRequest)(nil), "pb.GroupSettingRequest")
	proto.RegisterType((*GroupSettingReply)(nil), "pb.GroupSettingReply")
	proto.RegisterType((*Group)(nil), "pb.Group")
	proto.RegisterType((*GroupBot)(nil), "pb.GroupBot")
	proto.RegisterType((*GroupBotSetting)(nil), "pb.GroupBotSetting")
	proto.RegisterType((*GroupSetting)(nil), "pb.GroupSetting")
	proto.RegisterType((*GroupTag)(nil), "pb.GroupTag")
	proto.RegisterType((*Bot)(nil), "pb.Bot")
	proto.RegisterType((*BotRequest)(nil), "pb.BotRequest")
	proto.RegisterType((*BotReply)(nil), "pb.BotReply")
	proto.RegisterType((*BotsRequest)(nil), "pb.BotsRequest")
	proto.RegisterType((*BotsReply)(nil), "pb.BotsReply")
	proto.RegisterType((*GroupRequest)(nil), "pb.GroupRequest")
	proto.RegisterType((*GroupReply)(nil), "pb.GroupReply")
	proto.RegisterType((*GroupItem)(nil), "pb.GroupItem")
	proto.RegisterType((*LastMessage)(nil), "pb.LastMessage")
	proto.RegisterType((*GetGroupsReply)(nil), "pb.GetGroupsReply")
	proto.RegisterType((*GetGroupReply)(nil), "pb.GetGroupReply")
}

func init() { proto.RegisterFile("chatbot.proto", fileDescriptor_acc44097314201ac) }

var fileDescriptor_acc44097314201ac = []byte{
	// 1128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x8f, 0xed, 0xda, 0x89, 0x9f, 0xd3, 0xb4, 0x9d, 0x6e, 0x77, 0xb3, 0x85, 0xcd, 0x76, 0x0d,
	0x2b, 0x55, 0x02, 0x5a, 0xb6, 0x8b, 0xd4, 0x23, 0x34, 0x45, 0xea, 0x46, 0xc0, 0xc5, 0x65, 0x39,
	0x20, 0xa1, 0x6a, 0x1c, 0x0f, 0xc1, 0xda, 0xd4, 0x0e, 0xf1, 0xb8, 0xa2, 0x47, 0x0e, 0x5c, 0xb8,
	0xc0, 0x09, 0x89, 0x8f, 0xc0, 0x37, 0xe1, 0xb8, 0x47, 0x4e, 0x48, 0xab, 0x7e, 0x01, 0x3e, 0x02,
	0x9a, 0x37, 0x33, 0x8e, 0x9d, 0xe6, 0x4f, 0xbb, 0xbb, 0x37, 0xbf, 0xdf, 0xbc, 0x3f, 0xbf, 0x79,
	0xff, 0x26, 0x81, 0xd5, 0xfe, 0x0f, 0x94, 0x87, 0x29, 0xdf, 0x1b, 0x8d, 0x53, 0x9e, 0x12, 0x73,
	0x14, 0x6e, 0x43, 0x48, 0x33, 0x26, 0xe5, 0xed, 0x3b, 0x83, 0x74, 0x90, 0xe2, 0xe7, 0xbe, 0xf8,
	0x92, 0xa8, 0x1f, 0x40, 0xeb, 0x58, 0x9a, 0x05, 0xec, 0xc7, 0x9c, 0x65, 0x9c, 0x3c, 0x00, 0x38,
	0x67, 0x59, 0x46, 0x07, 0xec, 0x2c, 0x8e, 0xda, 0xc6, 0x8e, 0xb1, 0x6b, 0x05, 0xae, 0x42, 0x7a,
	0x11, 0x79, 0x04, 0x4d, 0x7d, 0x9c, 0xe7, 0x71, 0xd4, 0x36, 0x77, 0x8c, 0x5d, 0x37, 0xf0, 0x14,
	0xf6, 0x3c, 0x8f, 0x23, 0xff, 0x7d, 0x68, 0x16, 0x3e, 0x47, 0xc3, 0x4b, 0x72, 0x07, 0xec, 0x8c,
	0x53, 0xce, 0xd0, 0x59, 0x23, 0x90, 0x82, 0x7f, 0x02, 0x6b, 0x27, 0xe3, 0x34, 0x1f, 0x75, 0x27,
	0xa1, 0xef, 0x43, 0x63, 0x20, 0xa0, 0x49, 0xe0, 0x3a, 0xca, 0xbd, 0x88, 0xdc, 0x07, 0x2b, 0x4c,
	0x39, 0x46, 0xf3, 0x0e, 0xea, 0x7b, 0xa3, 0x70, 0x4f, 0xd8, 0x09, 0xcc, 0xff, 0xd3, 0x80, 0x8d,
	0x6e, 0xca, 0x4f, 0x19, 0xe7, 0x71, 0x32, 0xb8, 0x81, 0xaf, 0x07, 0x00, 0xf2, 0xa8, 0x74, 0x01,
	0x17, 0x11, 0x41, 0x9f, 0x6c, 0x81, 0x13, 0xa6, 0x5c, 0xd8, 0x59, 0x68, 0x67, 0x87, 0x29, 0x47,
	0x06, 0x0d, 0x01, 0xa3, 0xcd, 0x0a, 0xda, 0xd4, 0xc3, 0x94, 0xa3, 0x45, 0x1b, 0xac, 0x17, 0x17,
	0x59, 0xdb, 0xde, 0xb1, 0x76, 0xbd, 0x03, 0x47, 0x90, 0xfb, 0xe2, 0x9b, 0x40, 0x40, 0xfe, 0x77,
	0xb0, 0x56, 0xa6, 0x26, 0xb2, 0xb1, 0x80, 0xd8, 0x24, 0xb2, 0x59, 0x8e, 0xac, 0xdc, 0x5b, 0xd7,
	0xdd, 0xc7, 0xb0, 0x89, 0x39, 0x7c, 0x6b, 0x77, 0x9f, 0x1f, 0x6a, 0x00, 0x1b, 0xd5, 0x50, 0x4b,
	0xee, 0xf2, 0xda, 0x81, 0xfe, 0x35, 0xc0, 0xc6, 0x48, 0xa4, 0x05, 0x66, 0xe1, 0xd7, 0x8c, 0x23,
	0xb2, 0x0d, 0x8d, 0x4c, 0xdc, 0x30, 0xe9, 0x33, 0x95, 0xa0, 0x42, 0x26, 0x04, 0x56, 0xf8, 0xe5,
	0x88, 0x61, 0xc9, 0xec, 0x00, 0xbf, 0x05, 0x56, 0xaa, 0x16, 0x7e, 0x93, 0x7b, 0x50, 0xcf, 0x33,
	0x36, 0x16, 0x84, 0x6d, 0x74, 0xe1, 0x08, 0xb1, 0x17, 0x09, 0xe5, 0x84, 0x9e, 0xb3, 0xb6, 0x23,
	0x95, 0xc5, 0x37, 0xb9, 0x0b, 0x0e, 0xbd, 0xa0, 0x9c, 0x8e, 0xdb, 0x75, 0x44, 0x95, 0x24, 0xee,
	0xd6, 0x1f, 0x33, 0xca, 0x59, 0x74, 0x46, 0x79, 0xbb, 0x21, 0x47, 0x44, 0x21, 0x47, 0x38, 0x41,
	0xf9, 0x28, 0xd2, 0xc7, 0xae, 0x3c, 0x56, 0xc8, 0x11, 0xf7, 0x7f, 0x35, 0xa0, 0xa1, 0x3b, 0xff,
	0xda, 0x1d, 0xcb, 0x19, 0x35, 0xe7, 0x75, 0x47, 0xa5, 0x2f, 0xab, 0x64, 0x56, 0x16, 0x93, 0xb1,
	0xa7, 0xc9, 0xfc, 0x65, 0x4c, 0xc6, 0x50, 0x95, 0xf6, 0x35, 0x3a, 0x74, 0x1d, 0xac, 0x17, 0xec,
	0x12, 0x79, 0xb9, 0x81, 0xf8, 0x14, 0x33, 0x7f, 0x41, 0x87, 0x39, 0x53, 0xc9, 0x97, 0xc2, 0x14,
	0x57, 0x7b, 0x31, 0x57, 0x67, 0x9a, 0xeb, 0x6f, 0x06, 0x34, 0xcb, 0x3d, 0xb8, 0x88, 0xa8, 0x62,
	0x64, 0xce, 0x60, 0x64, 0xcd, 0x67, 0x74, 0xdb, 0xec, 0xfd, 0xa2, 0x4b, 0xf9, 0x35, 0x1d, 0xdc,
	0xa6, 0x94, 0xeb, 0x60, 0x71, 0x3a, 0xd0, 0xf9, 0xe2, 0x74, 0xf0, 0x86, 0x3c, 0xfe, 0x30, 0xc1,
	0x9a, 0xd5, 0x4d, 0x7a, 0x02, 0xcc, 0xd2, 0x04, 0xe8, 0x46, 0x5f, 0x29, 0x35, 0x7a, 0x07, 0x20,
	0x8e, 0x58, 0xc2, 0xe3, 0xef, 0x63, 0x36, 0x46, 0xf7, 0x6e, 0x50, 0x42, 0xc4, 0x20, 0x44, 0x8c,
	0xd3, 0x78, 0xa8, 0xc6, 0x43, 0x49, 0x73, 0x07, 0xe4, 0x2e, 0x38, 0xec, 0x27, 0xce, 0x92, 0x08,
	0x87, 0xc3, 0x0d, 0x94, 0x24, 0x70, 0xb1, 0xfc, 0xf3, 0x0c, 0xa7, 0xc2, 0x0e, 0x94, 0x34, 0x75,
	0x7b, 0x58, 0x7c, 0x7b, 0x6f, 0xea, 0xf6, 0x95, 0x44, 0x37, 0x2b, 0x89, 0xf6, 0x29, 0x40, 0xe5,
	0x7d, 0xc1, 0x47, 0xc4, 0xb8, 0xfe, 0x88, 0x2c, 0x5b, 0x57, 0xe5, 0xe5, 0x6f, 0x55, 0x96, 0xbf,
	0xff, 0x18, 0x1a, 0x5d, 0xfd, 0xd2, 0xcd, 0x0f, 0xe0, 0x9f, 0x80, 0xd7, 0x4d, 0x79, 0xf6, 0xc6,
	0x2b, 0xda, 0xdf, 0x05, 0x57, 0x3a, 0x12, 0x01, 0xdf, 0x81, 0x95, 0x30, 0xe5, 0x59, 0xdb, 0xc0,
	0x3d, 0x5a, 0x44, 0x44, 0xd0, 0xdf, 0x57, 0xe3, 0xa2, 0x63, 0x3e, 0x04, 0x1b, 0xdd, 0x28, 0x7e,
	0xae, 0xd0, 0x96, 0x0a, 0x12, 0xf7, 0x3f, 0x02, 0x50, 0x06, 0xc2, 0xf7, 0x52, 0xf5, 0x9f, 0x4d,
	0x70, 0x11, 0xe8, 0x71, 0x76, 0x5e, 0xd9, 0xce, 0xc6, 0x9c, 0xed, 0x6c, 0xce, 0xd8, 0xce, 0xd6,
	0x92, 0xde, 0x9c, 0xf4, 0x98, 0x5d, 0xe9, 0xb1, 0x47, 0xd0, 0xcc, 0x93, 0x31, 0xa3, 0xd1, 0x59,
	0x3f, 0xcd, 0x13, 0x8e, 0x1d, 0x68, 0x07, 0x9e, 0xc4, 0x8e, 0x05, 0x44, 0x0e, 0xa0, 0x39, 0xa4,
	0x19, 0x3f, 0x53, 0x3f, 0x4e, 0xb0, 0x19, 0xbd, 0x83, 0x35, 0x71, 0x91, 0x2f, 0x69, 0xc6, 0xbf,
	0x92, 0x70, 0xe0, 0x0d, 0x27, 0x82, 0xc8, 0xbe, 0xa8, 0xb4, 0x0a, 0xe9, 0xee, 0x58, 0x22, 0xfb,
	0x61, 0xca, 0x8f, 0x64, 0x54, 0x39, 0x61, 0xa0, 0x27, 0xcc, 0x7f, 0x06, 0x5e, 0xc9, 0x15, 0x79,
	0x08, 0xe8, 0xec, 0x2c, 0x63, 0x49, 0xc4, 0xc6, 0x98, 0x07, 0x37, 0x00, 0x01, 0x9d, 0x22, 0x42,
	0xda, 0x50, 0xef, 0xa7, 0x09, 0x67, 0x09, 0x57, 0x95, 0xd5, 0xa2, 0x7f, 0x08, 0xad, 0x13, 0xc6,
	0x31, 0x9f, 0xaa, 0xb8, 0x8f, 0xc1, 0xc1, 0x44, 0xeb, 0xf2, 0xae, 0x16, 0x15, 0x10, 0x09, 0x0f,
	0xd4, 0xa1, 0xff, 0x09, 0xac, 0x6a, 0x43, 0x69, 0xf7, 0x5e, 0xb5, 0x70, 0x53, 0x66, 0xf2, 0xec,
	0xe0, 0x3f, 0x07, 0x40, 0xfd, 0x4a, 0x3b, 0xbd, 0xe8, 0x93, 0x8f, 0xc1, 0x79, 0x46, 0x93, 0x68,
	0xc8, 0x08, 0x11, 0xea, 0xd5, 0xdf, 0x84, 0xdb, 0xeb, 0x15, 0x6c, 0x34, 0xbc, 0xf4, 0x6b, 0xe4,
	0x43, 0x68, 0x04, 0x6c, 0x10, 0x67, 0x9c, 0x8d, 0x49, 0x4b, 0x37, 0x9e, 0xd2, 0x47, 0xf9, 0x54,
	0xfc, 0xcc, 0xd3, 0xda, 0xbb, 0xe0, 0x9c, 0x30, 0x8e, 0x3b, 0x6a, 0x4a, 0xb7, 0x59, 0xc8, 0x52,
	0xf3, 0x03, 0xa8, 0x4b, 0xcd, 0x8c, 0xac, 0xa9, 0x23, 0x3d, 0x35, 0xdb, 0xab, 0x13, 0x40, 0x2a,
	0x1f, 0x42, 0xeb, 0x18, 0xd7, 0x44, 0xf1, 0xa0, 0x6e, 0x16, 0xb7, 0x5d, 0xc8, 0xe7, 0x10, 0x5a,
	0x9f, 0xb3, 0x21, 0xbb, 0xbd, 0xe1, 0x67, 0xb0, 0xf5, 0x1c, 0x37, 0xcf, 0xf4, 0xab, 0xb9, 0xa5,
	0xb8, 0x55, 0x7f, 0x8b, 0xcd, 0xf0, 0xf0, 0x29, 0x90, 0x92, 0x07, 0x6d, 0x7e, 0xaf, 0x08, 0xbf,
	0xd4, 0x41, 0x17, 0x88, 0x2e, 0xf8, 0xf2, 0xf8, 0x9b, 0xd3, 0xb0, 0xf4, 0x71, 0x0c, 0x6b, 0xda,
	0xc7, 0x52, 0x06, 0x5b, 0xd7, 0x0f, 0xa4, 0x93, 0xa7, 0xe0, 0x16, 0x2d, 0x4b, 0xd6, 0x27, 0xfb,
	0x41, 0xd9, 0x61, 0x27, 0x55, 0x7b, 0xda, 0xaf, 0x91, 0x27, 0xe0, 0x95, 0x4a, 0x36, 0xc3, 0xec,
	0xfa, 0x85, 0x9f, 0x40, 0x43, 0xbb, 0x99, 0xa1, 0xbf, 0x51, 0x0e, 0x33, 0xe9, 0x4e, 0xd0, 0x50,
	0x2f, 0x92, 0x8d, 0x24, 0xb6, 0xa7, 0xb6, 0xf1, 0x04, 0xd0, 0x8b, 0x4a, 0x9c, 0x4a, 0xdd, 0x70,
	0x43, 0x4e, 0x5e, 0xa9, 0x8a, 0x37, 0x31, 0xe9, 0xbe, 0xfb, 0xf7, 0xab, 0x8e, 0xf1, 0xf2, 0x55,
	0xa7, 0xf6, 0xfb, 0x55, 0xa7, 0xf6, 0xf2, 0xaa, 0x53, 0xfb, 0xe7, 0xaa, 0x53, 0xfb, 0xd6, 0xa1,
	0xa3, 0x78, 0x7f, 0x14, 0x86, 0x0e, 0xfe, 0x21, 0x7b, 0xfa, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x0f, 0x43, 0x44, 0x75, 0xc7, 0x0d, 0x00, 0x00,
}
