// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Channel              string   `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type MessageReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Time                 string   `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReply) Reset()         { *m = MessageReply{} }
func (m *MessageReply) String() string { return proto.CompactTextString(m) }
func (*MessageReply) ProtoMessage()    {}
func (*MessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *MessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReply.Unmarshal(m, b)
}
func (m *MessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReply.Marshal(b, m, deterministic)
}
func (m *MessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReply.Merge(m, src)
}
func (m *MessageReply) XXX_Size() int {
	return xxx_messageInfo_MessageReply.Size(m)
}
func (m *MessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReply proto.InternalMessageInfo

func (m *MessageReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MessageReply) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageReply) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type TextsReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Text                 []string `protobuf:"bytes,3,rep,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextsReply) Reset()         { *m = TextsReply{} }
func (m *TextsReply) String() string { return proto.CompactTextString(m) }
func (*TextsReply) ProtoMessage()    {}
func (*TextsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}
func (m *TextsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextsReply.Unmarshal(m, b)
}
func (m *TextsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextsReply.Marshal(b, m, deterministic)
}
func (m *TextsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextsReply.Merge(m, src)
}
func (m *TextsReply) XXX_Size() int {
	return xxx_messageInfo_TextsReply.Size(m)
}
func (m *TextsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TextsReply.DiscardUnknown(m)
}

var xxx_messageInfo_TextsReply proto.InternalMessageInfo

func (m *TextsReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TextsReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TextsReply) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

type MessageListReply struct {
	Messages             []*MessageItem `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageListReply) Reset()         { *m = MessageListReply{} }
func (m *MessageListReply) String() string { return proto.CompactTextString(m) }
func (*MessageListReply) ProtoMessage()    {}
func (*MessageListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}
func (m *MessageListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageListReply.Unmarshal(m, b)
}
func (m *MessageListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageListReply.Marshal(b, m, deterministic)
}
func (m *MessageListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageListReply.Merge(m, src)
}
func (m *MessageListReply) XXX_Size() int {
	return xxx_messageInfo_MessageListReply.Size(m)
}
func (m *MessageListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageListReply.DiscardUnknown(m)
}

var xxx_messageInfo_MessageListReply proto.InternalMessageInfo

func (m *MessageListReply) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

type MessageItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Time                 string   `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageItem) Reset()         { *m = MessageItem{} }
func (m *MessageItem) String() string { return proto.CompactTextString(m) }
func (*MessageItem) ProtoMessage()    {}
func (*MessageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}
func (m *MessageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageItem.Unmarshal(m, b)
}
func (m *MessageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageItem.Marshal(b, m, deterministic)
}
func (m *MessageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageItem.Merge(m, src)
}
func (m *MessageItem) XXX_Size() int {
	return xxx_messageInfo_MessageItem.Size(m)
}
func (m *MessageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageItem.DiscardUnknown(m)
}

var xxx_messageInfo_MessageItem proto.InternalMessageInfo

func (m *MessageItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageItem) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MessageItem) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageItem) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type Action struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Action) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ActionReply struct {
	Items                []*Action `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ActionReply) Reset()         { *m = ActionReply{} }
func (m *ActionReply) String() string { return proto.CompactTextString(m) }
func (*ActionReply) ProtoMessage()    {}
func (*ActionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}
func (m *ActionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionReply.Unmarshal(m, b)
}
func (m *ActionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionReply.Marshal(b, m, deterministic)
}
func (m *ActionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionReply.Merge(m, src)
}
func (m *ActionReply) XXX_Size() int {
	return xxx_messageInfo_ActionReply.Size(m)
}
func (m *ActionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ActionReply proto.InternalMessageInfo

func (m *ActionReply) GetItems() []*Action {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "pb.MessageRequest")
	proto.RegisterType((*MessageReply)(nil), "pb.MessageReply")
	proto.RegisterType((*TextsReply)(nil), "pb.TextsReply")
	proto.RegisterType((*MessageListReply)(nil), "pb.MessageListReply")
	proto.RegisterType((*MessageItem)(nil), "pb.MessageItem")
	proto.RegisterType((*Action)(nil), "pb.Action")
	proto.RegisterType((*ActionReply)(nil), "pb.ActionReply")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4b, 0xcb, 0xd3, 0x40,
	0x14, 0x35, 0x8f, 0xa6, 0xf5, 0xd6, 0x3e, 0x1c, 0x15, 0x86, 0xae, 0x42, 0x56, 0x45, 0x6b, 0x0a,
	0x75, 0xa1, 0x1b, 0x11, 0xb5, 0x50, 0x04, 0xdd, 0xa4, 0x82, 0xe0, 0x2e, 0x69, 0xae, 0x3a, 0x98,
	0x97, 0x9d, 0x09, 0xb6, 0xbf, 0xf4, 0xfb, 0x3b, 0x1f, 0x99, 0x99, 0xa4, 0x29, 0x6d, 0xa1, 0x14,
	0xbe, 0xdd, 0x9d, 0x73, 0xcf, 0x39, 0xf7, 0x9e, 0xdb, 0x12, 0x18, 0xa4, 0xc8, 0x79, 0xf8, 0x1b,
	0xfd, 0x62, 0x9b, 0x8b, 0x9c, 0x98, 0x45, 0x34, 0x81, 0x28, 0xe4, 0xfa, 0xed, 0x45, 0x30, 0xfc,
	0xa6, 0x08, 0x01, 0xfe, 0x2b, 0x91, 0x0b, 0x32, 0x04, 0x93, 0xc5, 0xd4, 0x70, 0x8d, 0xa9, 0x15,
	0x98, 0x2c, 0x26, 0x04, 0xec, 0xb2, 0x64, 0x31, 0x35, 0x5d, 0x63, 0xfa, 0x38, 0x90, 0x75, 0x85,
	0x09, 0xdc, 0x09, 0x6a, 0x29, 0xac, 0xaa, 0x09, 0x85, 0xee, 0xe6, 0x4f, 0x98, 0x65, 0x98, 0x50,
	0x5b, 0xc2, 0xf5, 0xd3, 0xcb, 0xe0, 0x49, 0x33, 0xa3, 0x48, 0xf6, 0x37, 0x4f, 0xa8, 0xb0, 0x7d,
	0x81, 0xda, 0x5e, 0xd6, 0x12, 0x63, 0x29, 0xd2, 0x8e, 0xc6, 0x58, 0x8a, 0xde, 0x12, 0xe0, 0x3b,
	0xee, 0x04, 0xbf, 0x65, 0x9a, 0x55, 0x4f, 0xf3, 0x3e, 0xc0, 0x58, 0x6f, 0xfd, 0x95, 0x71, 0xa1,
	0xbc, 0x5e, 0x41, 0x4f, 0x9f, 0x93, 0x53, 0xd3, 0xb5, 0xa6, 0xfd, 0xc5, 0xc8, 0x2f, 0x22, 0x5f,
	0xf3, 0xbe, 0x08, 0x4c, 0x83, 0x86, 0xe0, 0xa5, 0xd0, 0x6f, 0x35, 0x1e, 0x3c, 0xf5, 0x0c, 0x9c,
	0x8f, 0x1b, 0xc1, 0xf2, 0xec, 0xdc, 0x24, 0xe9, 0x6a, 0x1e, 0x5c, 0xbd, 0x39, 0xf4, 0x15, 0x5b,
	0x05, 0x73, 0xa1, 0xc3, 0x04, 0xa6, 0x9c, 0x1a, 0x32, 0x15, 0x54, 0xa9, 0x74, 0x5f, 0x35, 0x16,
	0x77, 0x16, 0x74, 0x75, 0x1c, 0xb2, 0x00, 0xbb, 0xba, 0x09, 0x21, 0xad, 0xf0, 0xfa, 0xef, 0x33,
	0x79, 0xde, 0xc2, 0x9a, 0xc3, 0x79, 0x8f, 0xc8, 0x6b, 0xb0, 0x56, 0x78, 0x5e, 0x32, 0x3e, 0xc2,
	0x14, 0xdd, 0x07, 0xe7, 0xf3, 0x16, 0x43, 0x81, 0x67, 0x15, 0xc3, 0x0a, 0x3b, 0xfc, 0xc6, 0xd2,
	0xde, 0x59, 0x62, 0x82, 0x17, 0xf8, 0x83, 0x9a, 0x5f, 0xd3, 0x67, 0x60, 0xaf, 0x31, 0x8b, 0x2f,
	0x9b, 0xaf, 0x45, 0x28, 0x9a, 0x65, 0x5e, 0x82, 0x15, 0x94, 0xd9, 0x75, 0xce, 0x6f, 0xe1, 0xe9,
	0x0a, 0x85, 0xba, 0x9d, 0xe6, 0x72, 0x32, 0x3a, 0xb0, 0x94, 0x6c, 0xd4, 0x3a, 0xb0, 0x16, 0xbe,
	0x83, 0x67, 0x2a, 0xf1, 0x91, 0xf6, 0x54, 0x7a, 0xba, 0xde, 0x7b, 0x78, 0xa1, 0xb2, 0xff, 0xc8,
	0xb7, 0x7f, 0x7f, 0x25, 0xf9, 0xff, 0x5a, 0x7b, 0x55, 0xba, 0x4f, 0xbd, 0x9f, 0x4e, 0x58, 0xb0,
	0x79, 0x11, 0x45, 0x8e, 0xfc, 0x26, 0xbc, 0xb9, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xcc, 0xd6,
	0x0e, 0x34, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageClient interface {
	List(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageListReply, error)
	Get(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageReply, error)
	Create(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*TextsReply, error)
	Delete(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*TextReply, error)
	Send(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*StateReply, error)
	Run(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*TextReply, error)
	GetActionMessages(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*ActionReply, error)
	CreateActionMessage(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*StateReply, error)
	DeleteWorkflowMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*StateReply, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) List(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageListReply, error) {
	out := new(MessageListReply)
	err := c.cc.Invoke(ctx, "/pb.Message/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) Get(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, "/pb.Message/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) Create(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*TextsReply, error) {
	out := new(TextsReply)
	err := c.cc.Invoke(ctx, "/pb.Message/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) Delete(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*TextReply, error) {
	out := new(TextReply)
	err := c.cc.Invoke(ctx, "/pb.Message/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) Send(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Message/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) Run(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*TextReply, error) {
	out := new(TextReply)
	err := c.cc.Invoke(ctx, "/pb.Message/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetActionMessages(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*ActionReply, error) {
	out := new(ActionReply)
	err := c.cc.Invoke(ctx, "/pb.Message/GetActionMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) CreateActionMessage(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Message/CreateActionMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) DeleteWorkflowMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Message/DeleteWorkflowMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
type MessageServer interface {
	List(context.Context, *MessageRequest) (*MessageListReply, error)
	Get(context.Context, *MessageRequest) (*MessageReply, error)
	Create(context.Context, *MessageRequest) (*TextsReply, error)
	Delete(context.Context, *MessageRequest) (*TextReply, error)
	Send(context.Context, *MessageRequest) (*StateReply, error)
	Run(context.Context, *MessageRequest) (*TextReply, error)
	GetActionMessages(context.Context, *TextRequest) (*ActionReply, error)
	CreateActionMessage(context.Context, *TextRequest) (*StateReply, error)
	DeleteWorkflowMessage(context.Context, *MessageRequest) (*StateReply, error)
}

// UnimplementedMessageServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (*UnimplementedMessageServer) List(ctx context.Context, req *MessageRequest) (*MessageListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedMessageServer) Get(ctx context.Context, req *MessageRequest) (*MessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMessageServer) Create(ctx context.Context, req *MessageRequest) (*TextsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedMessageServer) Delete(ctx context.Context, req *MessageRequest) (*TextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedMessageServer) Send(ctx context.Context, req *MessageRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedMessageServer) Run(ctx context.Context, req *MessageRequest) (*TextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (*UnimplementedMessageServer) GetActionMessages(ctx context.Context, req *TextRequest) (*ActionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActionMessages not implemented")
}
func (*UnimplementedMessageServer) CreateActionMessage(ctx context.Context, req *TextRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateActionMessage not implemented")
}
func (*UnimplementedMessageServer) DeleteWorkflowMessage(ctx context.Context, req *MessageRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkflowMessage not implemented")
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).List(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Get(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Create(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Delete(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Send(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Run(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetActionMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetActionMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/GetActionMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetActionMessages(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_CreateActionMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).CreateActionMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/CreateActionMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).CreateActionMessage(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_DeleteWorkflowMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).DeleteWorkflowMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/DeleteWorkflowMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).DeleteWorkflowMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Message_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Message_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Message_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Message_Delete_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Message_Send_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _Message_Run_Handler,
		},
		{
			MethodName: "GetActionMessages",
			Handler:    _Message_GetActionMessages_Handler,
		},
		{
			MethodName: "CreateActionMessage",
			Handler:    _Message_CreateActionMessage_Handler,
		},
		{
			MethodName: "DeleteWorkflowMessage",
			Handler:    _Message_DeleteWorkflowMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
