// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Notification_Priority int32

const (
	PRIORITY_UNSPECIFIED Notification_Priority = 0
	PRIORITY_NORMAL      Notification_Priority = 1
	PRIORITY_HIGH        Notification_Priority = 2
)

var Notification_Priority_name = map[int32]string{
	0: "PRIORITY_UNSPECIFIED",
	1: "PRIORITY_NORMAL",
	2: "PRIORITY_HIGH",
}

var Notification_Priority_value = map[string]int32{
	"PRIORITY_UNSPECIFIED": 0,
	"PRIORITY_NORMAL":      1,
	"PRIORITY_HIGH":        2,
}

func (x Notification_Priority) String() string {
	return proto.EnumName(Notification_Priority_name, int32(x))
}

func (Notification_Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12, 0}
}

type MessageRequest struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type MessageReply struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *MessageReply) Reset()         { *m = MessageReply{} }
func (m *MessageReply) String() string { return proto.CompactTextString(m) }
func (*MessageReply) ProtoMessage()    {}
func (*MessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *MessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReply.Unmarshal(m, b)
}
func (m *MessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReply.Marshal(b, m, deterministic)
}
func (m *MessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReply.Merge(m, src)
}
func (m *MessageReply) XXX_Size() int {
	return xxx_messageInfo_MessageReply.Size(m)
}
func (m *MessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReply proto.InternalMessageInfo

func (m *MessageReply) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type MessagesReply struct {
	Messages []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (m *MessagesReply) Reset()         { *m = MessagesReply{} }
func (m *MessagesReply) String() string { return proto.CompactTextString(m) }
func (*MessagesReply) ProtoMessage()    {}
func (*MessagesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}
func (m *MessagesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesReply.Unmarshal(m, b)
}
func (m *MessagesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesReply.Marshal(b, m, deterministic)
}
func (m *MessagesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesReply.Merge(m, src)
}
func (m *MessagesReply) XXX_Size() int {
	return xxx_messageInfo_MessagesReply.Size(m)
}
func (m *MessagesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesReply.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesReply proto.InternalMessageInfo

func (m *MessagesReply) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"user_id"
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" db:"user_id"`
	// @inject_tag: db:"sequence"
	Sequence int64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty" db:"sequence"`
	// @inject_tag: db:"uuid"
	Uuid string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty" db:"uuid"`
	// @inject_tag: db:"sender"
	Sender int64 `protobuf:"varint,5,opt,name=sender,proto3" json:"sender,omitempty" db:"sender"`
	// @inject_tag: db:"sender_type"
	SenderType string `protobuf:"bytes,6,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty" db:"sender_type"`
	// @inject_tag: db:"receiver"
	Receiver int64 `protobuf:"varint,7,opt,name=receiver,proto3" json:"receiver,omitempty" db:"receiver"`
	// @inject_tag: db:"receiver_type"
	ReceiverType string `protobuf:"bytes,8,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty" db:"receiver_type"`
	// @inject_tag: db:"type"
	Type string `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty" db:"type"`
	// @inject_tag: db:"text"
	Text string `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty" db:"text"`
	// @inject_tag: db:"status"
	Status int32 `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty" db:"status"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Message) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Message) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Message) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *Message) GetSenderType() string {
	if m != nil {
		return m.SenderType
	}
	return ""
}

func (m *Message) GetReceiver() int64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *Message) GetReceiverType() string {
	if m != nil {
		return m.ReceiverType
	}
	return ""
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Message) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Message) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Group struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"sequence"
	Sequence int64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty" db:"sequence"`
	// @inject_tag: db:"type"
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty" db:"type"`
	// @inject_tag: db:"uuid"
	Uuid string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty" db:"uuid"`
	// @inject_tag: db:"user_id"
	UserId int64 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" db:"user_id"`
	// @inject_tag: db:"name"
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty" db:"name"`
	// @inject_tag: db:"avatar"
	Avatar string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty" db:"avatar"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Group) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Group) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Group) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Group) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Group) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GroupBot struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"group_id"
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id"`
	// @inject_tag: db:"bot_id"
	BotId int64 `protobuf:"varint,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty" db:"bot_id"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *GroupBot) Reset()         { *m = GroupBot{} }
func (m *GroupBot) String() string { return proto.CompactTextString(m) }
func (*GroupBot) ProtoMessage()    {}
func (*GroupBot) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}
func (m *GroupBot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupBot.Unmarshal(m, b)
}
func (m *GroupBot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupBot.Marshal(b, m, deterministic)
}
func (m *GroupBot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupBot.Merge(m, src)
}
func (m *GroupBot) XXX_Size() int {
	return xxx_messageInfo_GroupBot.Size(m)
}
func (m *GroupBot) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupBot.DiscardUnknown(m)
}

var xxx_messageInfo_GroupBot proto.InternalMessageInfo

func (m *GroupBot) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupBot) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupBot) GetBotId() int64 {
	if m != nil {
		return m.BotId
	}
	return 0
}

func (m *GroupBot) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GroupBot) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GroupBotSetting struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"group_id"
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id"`
	// @inject_tag: db:"bot_id"
	BotId int64 `protobuf:"varint,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty" db:"bot_id"`
	// @inject_tag: db:"key"
	Key string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty" db:"key"`
	// @inject_tag: db:"value"
	Value string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty" db:"value"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *GroupBotSetting) Reset()         { *m = GroupBotSetting{} }
func (m *GroupBotSetting) String() string { return proto.CompactTextString(m) }
func (*GroupBotSetting) ProtoMessage()    {}
func (*GroupBotSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}
func (m *GroupBotSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupBotSetting.Unmarshal(m, b)
}
func (m *GroupBotSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupBotSetting.Marshal(b, m, deterministic)
}
func (m *GroupBotSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupBotSetting.Merge(m, src)
}
func (m *GroupBotSetting) XXX_Size() int {
	return xxx_messageInfo_GroupBotSetting.Size(m)
}
func (m *GroupBotSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupBotSetting.DiscardUnknown(m)
}

var xxx_messageInfo_GroupBotSetting proto.InternalMessageInfo

func (m *GroupBotSetting) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupBotSetting) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupBotSetting) GetBotId() int64 {
	if m != nil {
		return m.BotId
	}
	return 0
}

func (m *GroupBotSetting) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GroupBotSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GroupBotSetting) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GroupBotSetting) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GroupSetting struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"group_id"
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id"`
	// @inject_tag: db:"key"
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty" db:"key"`
	// @inject_tag: db:"value"
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty" db:"value"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *GroupSetting) Reset()         { *m = GroupSetting{} }
func (m *GroupSetting) String() string { return proto.CompactTextString(m) }
func (*GroupSetting) ProtoMessage()    {}
func (*GroupSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}
func (m *GroupSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupSetting.Unmarshal(m, b)
}
func (m *GroupSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupSetting.Marshal(b, m, deterministic)
}
func (m *GroupSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSetting.Merge(m, src)
}
func (m *GroupSetting) XXX_Size() int {
	return xxx_messageInfo_GroupSetting.Size(m)
}
func (m *GroupSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSetting.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSetting proto.InternalMessageInfo

func (m *GroupSetting) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupSetting) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupSetting) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GroupSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GroupSetting) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GroupSetting) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GroupTag struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"group_id"
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" db:"group_id"`
	// @inject_tag: db:"tag"
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty" db:"tag"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at"`
}

func (m *GroupTag) Reset()         { *m = GroupTag{} }
func (m *GroupTag) String() string { return proto.CompactTextString(m) }
func (*GroupTag) ProtoMessage()    {}
func (*GroupTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}
func (m *GroupTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTag.Unmarshal(m, b)
}
func (m *GroupTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTag.Marshal(b, m, deterministic)
}
func (m *GroupTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTag.Merge(m, src)
}
func (m *GroupTag) XXX_Size() int {
	return xxx_messageInfo_GroupTag.Size(m)
}
func (m *GroupTag) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTag.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTag proto.InternalMessageInfo

func (m *GroupTag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupTag) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupTag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GroupTag) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GroupTag) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Action struct {
	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Action) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ActionReply struct {
	Items []*Action `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (m *ActionReply) Reset()         { *m = ActionReply{} }
func (m *ActionReply) String() string { return proto.CompactTextString(m) }
func (*ActionReply) ProtoMessage()    {}
func (*ActionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}
func (m *ActionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionReply.Unmarshal(m, b)
}
func (m *ActionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionReply.Marshal(b, m, deterministic)
}
func (m *ActionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionReply.Merge(m, src)
}
func (m *ActionReply) XXX_Size() int {
	return xxx_messageInfo_ActionReply.Size(m)
}
func (m *ActionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ActionReply proto.InternalMessageInfo

func (m *ActionReply) GetItems() []*Action {
	if m != nil {
		return m.Items
	}
	return nil
}

type Alert struct {
	Title        string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body         string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Subtitle     string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Action       string   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	ActionLocKey string   `protobuf:"bytes,5,opt,name=action_loc_key,json=actionLocKey,proto3" json:"action_loc_key,omitempty"`
	LaunchImage  string   `protobuf:"bytes,6,opt,name=launch_image,json=launchImage,proto3" json:"launch_image,omitempty"`
	LocKey       string   `protobuf:"bytes,7,opt,name=loc_key,json=locKey,proto3" json:"loc_key,omitempty"`
	TitleLocKey  string   `protobuf:"bytes,8,opt,name=title_loc_key,json=titleLocKey,proto3" json:"title_loc_key,omitempty"`
	LocArgs      []string `protobuf:"bytes,9,rep,name=loc_args,json=locArgs,proto3" json:"loc_args,omitempty"`
	TitleLocArgs []string `protobuf:"bytes,10,rep,name=title_loc_args,json=titleLocArgs,proto3" json:"title_loc_args,omitempty"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}
func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (m *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(m, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Alert) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Alert) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *Alert) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Alert) GetActionLocKey() string {
	if m != nil {
		return m.ActionLocKey
	}
	return ""
}

func (m *Alert) GetLaunchImage() string {
	if m != nil {
		return m.LaunchImage
	}
	return ""
}

func (m *Alert) GetLocKey() string {
	if m != nil {
		return m.LocKey
	}
	return ""
}

func (m *Alert) GetTitleLocKey() string {
	if m != nil {
		return m.TitleLocKey
	}
	return ""
}

func (m *Alert) GetLocArgs() []string {
	if m != nil {
		return m.LocArgs
	}
	return nil
}

func (m *Alert) GetTitleLocArgs() []string {
	if m != nil {
		return m.TitleLocArgs
	}
	return nil
}

type Notification struct {
	Tokens           []string              `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Platform         int32                 `protobuf:"varint,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Message          string                `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Title            string                `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Topic            string                `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	Key              string                `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Badge            int32                 `protobuf:"varint,7,opt,name=badge,proto3" json:"badge,omitempty"`
	Category         string                `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Alert            *Alert                `protobuf:"bytes,9,opt,name=alert,proto3" json:"alert,omitempty"`
	Sound            string                `protobuf:"bytes,10,opt,name=sound,proto3" json:"sound,omitempty"`
	ContentAvailable bool                  `protobuf:"varint,11,opt,name=content_available,json=contentAvailable,proto3" json:"content_available,omitempty"`
	ThreadId         string                `protobuf:"bytes,12,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	MutableContent   bool                  `protobuf:"varint,13,opt,name=mutable_content,json=mutableContent,proto3" json:"mutable_content,omitempty"`
	Image            string                `protobuf:"bytes,15,opt,name=image,proto3" json:"image,omitempty"`
	Priority         Notification_Priority `protobuf:"varint,16,opt,name=priority,proto3,enum=pb.Notification_Priority" json:"priority,omitempty"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *Notification) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *Notification) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Notification) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Notification) GetBadge() int32 {
	if m != nil {
		return m.Badge
	}
	return 0
}

func (m *Notification) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Notification) GetAlert() *Alert {
	if m != nil {
		return m.Alert
	}
	return nil
}

func (m *Notification) GetSound() string {
	if m != nil {
		return m.Sound
	}
	return ""
}

func (m *Notification) GetContentAvailable() bool {
	if m != nil {
		return m.ContentAvailable
	}
	return false
}

func (m *Notification) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

func (m *Notification) GetMutableContent() bool {
	if m != nil {
		return m.MutableContent
	}
	return false
}

func (m *Notification) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Notification) GetPriority() Notification_Priority {
	if m != nil {
		return m.Priority
	}
	return PRIORITY_UNSPECIFIED
}

type GroupRequest struct {
	Group *Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (m *GroupRequest) Reset()         { *m = GroupRequest{} }
func (m *GroupRequest) String() string { return proto.CompactTextString(m) }
func (*GroupRequest) ProtoMessage()    {}
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}
func (m *GroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupRequest.Unmarshal(m, b)
}
func (m *GroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupRequest.Marshal(b, m, deterministic)
}
func (m *GroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupRequest.Merge(m, src)
}
func (m *GroupRequest) XXX_Size() int {
	return xxx_messageInfo_GroupRequest.Size(m)
}
func (m *GroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupRequest proto.InternalMessageInfo

func (m *GroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupReply struct {
	Group *Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (m *GroupReply) Reset()         { *m = GroupReply{} }
func (m *GroupReply) String() string { return proto.CompactTextString(m) }
func (*GroupReply) ProtoMessage()    {}
func (*GroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}
func (m *GroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupReply.Unmarshal(m, b)
}
func (m *GroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupReply.Marshal(b, m, deterministic)
}
func (m *GroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupReply.Merge(m, src)
}
func (m *GroupReply) XXX_Size() int {
	return xxx_messageInfo_GroupReply.Size(m)
}
func (m *GroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_GroupReply proto.InternalMessageInfo

func (m *GroupReply) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupsReply struct {
	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (m *GroupsReply) Reset()         { *m = GroupsReply{} }
func (m *GroupsReply) String() string { return proto.CompactTextString(m) }
func (*GroupsReply) ProtoMessage()    {}
func (*GroupsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}
func (m *GroupsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupsReply.Unmarshal(m, b)
}
func (m *GroupsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupsReply.Marshal(b, m, deterministic)
}
func (m *GroupsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupsReply.Merge(m, src)
}
func (m *GroupsReply) XXX_Size() int {
	return xxx_messageInfo_GroupsReply.Size(m)
}
func (m *GroupsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GroupsReply proto.InternalMessageInfo

func (m *GroupsReply) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Notification_Priority", Notification_Priority_name, Notification_Priority_value)
	proto.RegisterType((*MessageRequest)(nil), "pb.MessageRequest")
	proto.RegisterType((*MessageReply)(nil), "pb.MessageReply")
	proto.RegisterType((*MessagesReply)(nil), "pb.MessagesReply")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*Group)(nil), "pb.Group")
	proto.RegisterType((*GroupBot)(nil), "pb.GroupBot")
	proto.RegisterType((*GroupBotSetting)(nil), "pb.GroupBotSetting")
	proto.RegisterType((*GroupSetting)(nil), "pb.GroupSetting")
	proto.RegisterType((*GroupTag)(nil), "pb.GroupTag")
	proto.RegisterType((*Action)(nil), "pb.Action")
	proto.RegisterType((*ActionReply)(nil), "pb.ActionReply")
	proto.RegisterType((*Alert)(nil), "pb.Alert")
	proto.RegisterType((*Notification)(nil), "pb.Notification")
	proto.RegisterType((*GroupRequest)(nil), "pb.GroupRequest")
	proto.RegisterType((*GroupReply)(nil), "pb.GroupReply")
	proto.RegisterType((*GroupsReply)(nil), "pb.GroupsReply")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 1218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x92, 0xdb, 0x44,
	0x10, 0xb6, 0x6c, 0x4b, 0x2b, 0xb5, 0xed, 0x5d, 0xef, 0xe4, 0x07, 0x65, 0x81, 0x8d, 0x23, 0xa0,
	0xb2, 0x05, 0xc9, 0x6e, 0x58, 0x2a, 0x95, 0x5c, 0x38, 0x38, 0x3f, 0x6c, 0x5c, 0x6c, 0x7e, 0x4a,
	0xbb, 0x14, 0x05, 0x17, 0xd7, 0x58, 0x9a, 0x38, 0xaa, 0xc8, 0x92, 0x90, 0x46, 0x4b, 0xfc, 0x00,
	0x5c, 0x38, 0xc1, 0x13, 0xf0, 0x02, 0xbc, 0x00, 0x6f, 0xc0, 0x31, 0x47, 0x8a, 0x03, 0x55, 0xa9,
	0xdc, 0x79, 0x06, 0x6a, 0xa6, 0x67, 0x64, 0xaf, 0x9d, 0x5d, 0x96, 0x9f, 0xdb, 0xf4, 0xd7, 0xdd,
	0x33, 0x5f, 0x77, 0x4f, 0xb7, 0x46, 0xd0, 0x99, 0xb0, 0xa2, 0xa0, 0x63, 0xb6, 0x9d, 0xe5, 0x29,
	0x4f, 0x49, 0x3d, 0x1b, 0x6d, 0xc0, 0x88, 0x16, 0x4a, 0xde, 0x38, 0x3f, 0x4e, 0xc7, 0xa9, 0x5c,
	0xee, 0x88, 0x15, 0xa2, 0xde, 0x2d, 0x58, 0x7d, 0x88, 0x6e, 0x3e, 0xfb, 0xa6, 0x64, 0x05, 0x27,
	0x1f, 0xc0, 0x8a, 0xda, 0xc8, 0x35, 0x7a, 0xc6, 0x56, 0x6b, 0xb7, 0xb5, 0x9d, 0x8d, 0xb6, 0xb5,
	0x91, 0xd6, 0x79, 0x37, 0xa1, 0x5d, 0x39, 0x66, 0xf1, 0xf4, 0xac, 0x6e, 0xb7, 0xa1, 0xa3, 0xb0,
	0x02, 0xfd, 0xae, 0x82, 0xad, 0x74, 0x85, 0x5b, 0xef, 0x35, 0x16, 0x1d, 0x2b, 0xa5, 0xf7, 0x7b,
	0x1d, 0x56, 0x14, 0x4a, 0x56, 0xa1, 0x1e, 0x85, 0xf2, 0x9c, 0x86, 0x5f, 0x8f, 0x42, 0xf2, 0x16,
	0xac, 0x94, 0x05, 0xcb, 0x87, 0x51, 0xe8, 0xd6, 0x25, 0x68, 0x09, 0x71, 0x10, 0x92, 0x0d, 0xb0,
	0x0b, 0x11, 0x57, 0x12, 0x30, 0xb7, 0x21, 0x35, 0x95, 0x4c, 0x08, 0x34, 0xcb, 0x32, 0x0a, 0xdd,
	0x66, 0xcf, 0xd8, 0x72, 0x7c, 0xb9, 0x26, 0x17, 0xc1, 0x2a, 0x58, 0x12, 0xb2, 0xdc, 0x35, 0x71,
	0x1f, 0x94, 0xc8, 0x65, 0x68, 0xe1, 0x6a, 0xc8, 0xa7, 0x19, 0x73, 0x2d, 0xe9, 0x02, 0x08, 0x1d,
	0x4e, 0x33, 0x26, 0x0e, 0xca, 0x59, 0xc0, 0xa2, 0x23, 0x96, 0xbb, 0x2b, 0x78, 0x90, 0x96, 0xc9,
	0x7b, 0xd0, 0xd1, 0x6b, 0x74, 0xb7, 0xa5, 0x7b, 0x5b, 0x83, 0x72, 0x03, 0x02, 0x4d, 0xa9, 0x73,
	0x90, 0x0d, 0xd7, 0x18, 0x7b, 0xc1, 0x5d, 0x50, 0x18, 0x7b, 0xc1, 0x25, 0x43, 0x4e, 0x79, 0x59,
	0xb8, 0xad, 0x9e, 0xb1, 0x65, 0xfa, 0x4a, 0x22, 0xef, 0x02, 0x04, 0x39, 0xa3, 0x9c, 0x85, 0x43,
	0xca, 0xdd, 0xb6, 0xa4, 0xe0, 0x28, 0xa4, 0xcf, 0x85, 0xba, 0xcc, 0x42, 0xad, 0xee, 0xa0, 0x5a,
	0x21, 0x7d, 0xee, 0xfd, 0x61, 0x80, 0xb9, 0x97, 0xa7, 0x65, 0xb6, 0x94, 0xda, 0xf9, 0x0c, 0xd6,
	0x97, 0x33, 0x28, 0x39, 0x37, 0x24, 0x93, 0x8a, 0xf3, 0x52, 0x56, 0xe7, 0xca, 0x63, 0x1e, 0x2b,
	0x0f, 0x81, 0x66, 0x42, 0x27, 0x3a, 0x9f, 0x72, 0x2d, 0x02, 0xa4, 0x47, 0x94, 0x53, 0xcc, 0xa3,
	0xe3, 0x2b, 0x69, 0x21, 0x40, 0xfb, 0xf4, 0x00, 0x9d, 0xc5, 0x00, 0xbf, 0x37, 0xc0, 0x96, 0x01,
	0xde, 0x49, 0xf9, 0x52, 0x8c, 0x97, 0xc0, 0x1e, 0x0b, 0xdd, 0xec, 0xfe, 0xac, 0x48, 0x79, 0x10,
	0x92, 0x0b, 0x60, 0x8d, 0x52, 0x2e, 0x14, 0x78, 0x7d, 0xcc, 0x51, 0xca, 0x07, 0xe1, 0x02, 0x99,
	0xe6, 0xe9, 0x64, 0xcc, 0x45, 0x32, 0xbf, 0x18, 0xb0, 0xa6, 0xc9, 0x1c, 0x30, 0xce, 0xa3, 0x64,
	0xfc, 0x3f, 0x70, 0xea, 0x42, 0xe3, 0x39, 0x9b, 0xaa, 0xc4, 0x8b, 0x25, 0x39, 0x0f, 0xe6, 0x11,
	0x8d, 0x4b, 0x26, 0x19, 0x38, 0x3e, 0x0a, 0x0b, 0xdc, 0xad, 0xd3, 0xb9, 0xaf, 0x2c, 0x72, 0xff,
	0xc9, 0x80, 0xb6, 0xe4, 0xfe, 0x2f, 0x88, 0x2b, 0x86, 0x8d, 0x37, 0x30, 0x6c, 0x9e, 0xcc, 0xd0,
	0x3c, 0x9d, 0xa1, 0xb5, 0xc8, 0xf0, 0x3b, 0x5d, 0xea, 0x43, 0xfa, 0x4f, 0xd9, 0x71, 0x3a, 0xd6,
	0xec, 0x38, 0x1d, 0xff, 0xc7, 0x2a, 0x5f, 0x03, 0xab, 0x1f, 0xf0, 0x28, 0x4d, 0x96, 0x48, 0xe8,
	0xbe, 0xae, 0xcf, 0xfa, 0xda, 0xdb, 0x81, 0x16, 0x5a, 0xe3, 0x58, 0xec, 0x81, 0x19, 0x71, 0x36,
	0x29, 0x5c, 0x43, 0xce, 0x44, 0x10, 0x33, 0x51, 0xe9, 0x51, 0xe1, 0xfd, 0x5c, 0x07, 0xb3, 0x1f,
	0xb3, 0x9c, 0x8b, 0x24, 0xf2, 0x88, 0xc7, 0x38, 0x78, 0x1d, 0x1f, 0x05, 0x71, 0xc8, 0x28, 0x0d,
	0xa7, 0xfa, 0x10, 0xb1, 0x96, 0xcd, 0x5c, 0x8e, 0xd0, 0x18, 0xe3, 0xac, 0x64, 0xd9, 0x77, 0xf2,
	0x00, 0x55, 0x0b, 0x25, 0x91, 0xf7, 0x61, 0x15, 0x57, 0xc3, 0x38, 0x0d, 0x86, 0xa2, 0x7e, 0x78,
	0x9b, 0xda, 0x88, 0xee, 0xa7, 0xc1, 0xe7, 0x6c, 0x4a, 0xae, 0x40, 0x3b, 0xa6, 0x65, 0x12, 0x3c,
	0x1b, 0x46, 0x13, 0xf1, 0x0d, 0xc0, 0x8e, 0x6e, 0x21, 0x36, 0x10, 0x90, 0x98, 0x02, 0x7a, 0x07,
	0xd5, 0xd9, 0x31, 0xfa, 0x7a, 0xd0, 0x91, 0x14, 0xaa, 0x03, 0x70, 0x3e, 0xb6, 0x24, 0xa8, 0xf6,
	0xbf, 0x04, 0xb6, 0xd0, 0xd2, 0x7c, 0x5c, 0xb8, 0x4e, 0xaf, 0xb1, 0xe5, 0xf8, 0x62, 0xb3, 0x7e,
	0x3e, 0x2e, 0x04, 0xc1, 0x99, 0xbb, 0x34, 0x00, 0x69, 0xd0, 0xd6, 0xfe, 0xc2, 0xca, 0xfb, 0xb1,
	0x09, 0xed, 0x47, 0x29, 0x8f, 0x9e, 0x46, 0x01, 0x95, 0x71, 0x5d, 0x04, 0x8b, 0xa7, 0xcf, 0x59,
	0x82, 0x29, 0x76, 0x7c, 0x25, 0x89, 0x1c, 0x65, 0x31, 0xe5, 0x4f, 0xd3, 0x7c, 0x22, 0x73, 0x67,
	0xfa, 0x95, 0x4c, 0xdc, 0xd9, 0x47, 0x0e, 0xd3, 0xa7, 0xc5, 0x59, 0x0d, 0x9a, 0xf3, 0x35, 0x10,
	0x68, 0x9a, 0x45, 0x81, 0x6e, 0x40, 0x29, 0xe8, 0x36, 0xb0, 0x8e, 0xb5, 0xc1, 0x88, 0x86, 0x63,
	0x26, 0x13, 0x63, 0xfa, 0x28, 0x08, 0x26, 0x01, 0xe5, 0x6c, 0x9c, 0xe6, 0x3a, 0x25, 0x95, 0x4c,
	0x2e, 0x83, 0x49, 0x45, 0xf1, 0xe5, 0xa4, 0x6b, 0xed, 0x3a, 0xf2, 0x7e, 0x08, 0xc0, 0x47, 0x5c,
	0x6c, 0x59, 0xa4, 0x65, 0x12, 0xaa, 0x8f, 0x07, 0x0a, 0xe4, 0x23, 0x58, 0x0f, 0xd2, 0x84, 0xb3,
	0x84, 0x0f, 0xe9, 0x11, 0x8d, 0x62, 0x3a, 0x8a, 0x99, 0xfc, 0x90, 0xd8, 0x7e, 0x57, 0x29, 0xfa,
	0x1a, 0x27, 0x6f, 0x83, 0xc3, 0x9f, 0xe5, 0x8c, 0x86, 0xa2, 0x59, 0xda, 0x48, 0x00, 0x81, 0x41,
	0x48, 0xae, 0xc2, 0xda, 0xa4, 0xe4, 0xc2, 0x6e, 0xa8, 0x1c, 0xe5, 0x57, 0xc5, 0xf6, 0x57, 0x15,
	0x7c, 0x17, 0x51, 0x41, 0x04, 0xaf, 0xc4, 0x1a, 0x12, 0x91, 0x02, 0xb9, 0x09, 0x76, 0x96, 0x47,
	0x69, 0x1e, 0xf1, 0xa9, 0xdb, 0xed, 0x19, 0x5b, 0xab, 0xbb, 0x97, 0x44, 0x08, 0xf3, 0x15, 0xda,
	0x7e, 0xa2, 0x0c, 0xfc, 0xca, 0xd4, 0xdb, 0x07, 0x5b, 0xa3, 0xc4, 0x85, 0xf3, 0x4f, 0xfc, 0xc1,
	0x63, 0x7f, 0x70, 0xf8, 0xd5, 0xf0, 0x8b, 0x47, 0x07, 0x4f, 0xee, 0xdf, 0x1d, 0x7c, 0x36, 0xb8,
	0x7f, 0xaf, 0x5b, 0x23, 0xe7, 0x60, 0xad, 0xd2, 0x3c, 0x7a, 0xec, 0x3f, 0xec, 0xef, 0x77, 0x0d,
	0xb2, 0x0e, 0x9d, 0x0a, 0x7c, 0x30, 0xd8, 0x7b, 0xd0, 0xad, 0x7b, 0x3b, 0x6a, 0x94, 0xe9, 0xa7,
	0xcf, 0x65, 0x30, 0xe5, 0x30, 0x50, 0x2f, 0x18, 0x99, 0x54, 0x34, 0x40, 0xdc, 0xbb, 0x0e, 0xa0,
	0x1c, 0x44, 0x8f, 0xfe, 0xad, 0xf9, 0x0d, 0x68, 0x49, 0x59, 0x3d, 0x75, 0xae, 0x80, 0x25, 0x71,
	0xdd, 0xd4, 0x73, 0x0e, 0x4a, 0xb1, 0xfb, 0x67, 0x13, 0x40, 0x3d, 0x72, 0x0e, 0x8e, 0x02, 0xb2,
	0x03, 0xcd, 0xfd, 0xa8, 0xe0, 0x84, 0xcc, 0x3f, 0x89, 0x90, 0xec, 0xc6, 0xfa, 0x1c, 0x86, 0x07,
	0x78, 0x35, 0x72, 0x1d, 0x1a, 0x7b, 0xec, 0xcd, 0xf6, 0xdd, 0x63, 0x18, 0x9a, 0xdf, 0x00, 0xeb,
	0xae, 0x1c, 0x67, 0x67, 0xf6, 0xb8, 0x0e, 0xd6, 0x3d, 0x16, 0xb3, 0x13, 0x3c, 0x3a, 0x02, 0x3b,
	0x64, 0x2f, 0xb8, 0x36, 0xbf, 0x06, 0xcd, 0x03, 0x96, 0x84, 0x6f, 0x34, 0x5e, 0x15, 0xd8, 0x01,
	0xa7, 0xbc, 0xda, 0xfc, 0x43, 0x68, 0xf8, 0x65, 0x72, 0xb6, 0x9d, 0x6f, 0xc1, 0xfa, 0x1e, 0xe3,
	0x38, 0x12, 0x75, 0x16, 0xc8, 0xda, 0xcc, 0x0a, 0xdd, 0xd6, 0xe6, 0xe6, 0xa6, 0x72, 0xbc, 0x0d,
	0xe7, 0x30, 0xe6, 0x63, 0xbe, 0xcb, 0xae, 0xcb, 0xf4, 0x3e, 0x85, 0x0b, 0x18, 0xfb, 0x97, 0x69,
	0xfe, 0xfc, 0x69, 0x9c, 0x7e, 0xab, 0x7d, 0xcf, 0x16, 0xdd, 0x0d, 0x70, 0xf6, 0x18, 0xc7, 0x0b,
	0x41, 0xba, 0xb3, 0xda, 0xcf, 0x53, 0x9d, 0xbb, 0x2e, 0x5e, 0x8d, 0x7c, 0x0c, 0x2d, 0xa4, 0x8a,
	0x4f, 0xb3, 0x65, 0x9f, 0xe5, 0x43, 0xb6, 0xc1, 0xd6, 0x87, 0x9c, 0x64, 0x3f, 0xbb, 0xc1, 0x5e,
	0xed, 0xce, 0x3b, 0xbf, 0xbe, 0xda, 0x34, 0x5e, 0xbe, 0xda, 0xac, 0xfd, 0xf0, 0x7a, 0xb3, 0xf6,
	0xf2, 0xf5, 0x66, 0xed, 0xb7, 0xd7, 0x9b, 0xb5, 0xaf, 0x2d, 0x9a, 0x45, 0x3b, 0xd9, 0x68, 0x64,
	0xc9, 0x9f, 0x84, 0x4f, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x0d, 0x2a, 0xa6, 0x5b, 0x0c,
	0x00, 0x00,
}
