// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: middle.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PageRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{0}
}
func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PageRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PageReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageReply) Reset()         { *m = PageReply{} }
func (m *PageReply) String() string { return proto.CompactTextString(m) }
func (*PageReply) ProtoMessage()    {}
func (*PageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{1}
}
func (m *PageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageReply.Unmarshal(m, b)
}
func (m *PageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageReply.Marshal(b, m, deterministic)
}
func (m *PageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageReply.Merge(m, src)
}
func (m *PageReply) XXX_Size() int {
	return xxx_messageInfo_PageReply.Size(m)
}
func (m *PageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PageReply.DiscardUnknown(m)
}

var xxx_messageInfo_PageReply proto.InternalMessageInfo

func (m *PageReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PageReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PageReply) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type AppRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppRequest) Reset()         { *m = AppRequest{} }
func (m *AppRequest) String() string { return proto.CompactTextString(m) }
func (*AppRequest) ProtoMessage()    {}
func (*AppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{2}
}
func (m *AppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppRequest.Unmarshal(m, b)
}
func (m *AppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppRequest.Marshal(b, m, deterministic)
}
func (m *AppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppRequest.Merge(m, src)
}
func (m *AppRequest) XXX_Size() int {
	return xxx_messageInfo_AppRequest.Size(m)
}
func (m *AppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppRequest proto.InternalMessageInfo

func (m *AppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AppRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AppRequest) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type AppsReply struct {
	Apps                 []*App   `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppsReply) Reset()         { *m = AppsReply{} }
func (m *AppsReply) String() string { return proto.CompactTextString(m) }
func (*AppsReply) ProtoMessage()    {}
func (*AppsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{3}
}
func (m *AppsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppsReply.Unmarshal(m, b)
}
func (m *AppsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppsReply.Marshal(b, m, deterministic)
}
func (m *AppsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppsReply.Merge(m, src)
}
func (m *AppsReply) XXX_Size() int {
	return xxx_messageInfo_AppsReply.Size(m)
}
func (m *AppsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AppsReply.DiscardUnknown(m)
}

var xxx_messageInfo_AppsReply proto.InternalMessageInfo

func (m *AppsReply) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AppReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Extra                []*KV    `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppReply) Reset()         { *m = AppReply{} }
func (m *AppReply) String() string { return proto.CompactTextString(m) }
func (*AppReply) ProtoMessage()    {}
func (*AppReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{4}
}
func (m *AppReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppReply.Unmarshal(m, b)
}
func (m *AppReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppReply.Marshal(b, m, deterministic)
}
func (m *AppReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppReply.Merge(m, src)
}
func (m *AppReply) XXX_Size() int {
	return xxx_messageInfo_AppReply.Size(m)
}
func (m *AppReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AppReply.DiscardUnknown(m)
}

var xxx_messageInfo_AppReply proto.InternalMessageInfo

func (m *AppReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AppReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AppReply) GetExtra() []*KV {
	if m != nil {
		return m.Extra
	}
	return nil
}

type App struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	IsAuthorized         bool     `protobuf:"varint,2,opt,name=isAuthorized,proto3" json:"isAuthorized,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{5}
}
func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *App) GetIsAuthorized() bool {
	if m != nil {
		return m.IsAuthorized
	}
	return false
}

func (m *App) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type CredentialsReply struct {
	Items                []*KV    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialsReply) Reset()         { *m = CredentialsReply{} }
func (m *CredentialsReply) String() string { return proto.CompactTextString(m) }
func (*CredentialsReply) ProtoMessage()    {}
func (*CredentialsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{6}
}
func (m *CredentialsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialsReply.Unmarshal(m, b)
}
func (m *CredentialsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialsReply.Marshal(b, m, deterministic)
}
func (m *CredentialsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialsReply.Merge(m, src)
}
func (m *CredentialsReply) XXX_Size() int {
	return xxx_messageInfo_CredentialsReply.Size(m)
}
func (m *CredentialsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialsReply.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialsReply proto.InternalMessageInfo

func (m *CredentialsReply) GetItems() []*KV {
	if m != nil {
		return m.Items
	}
	return nil
}

type CredentialRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialRequest) Reset()         { *m = CredentialRequest{} }
func (m *CredentialRequest) String() string { return proto.CompactTextString(m) }
func (*CredentialRequest) ProtoMessage()    {}
func (*CredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{7}
}
func (m *CredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialRequest.Unmarshal(m, b)
}
func (m *CredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialRequest.Marshal(b, m, deterministic)
}
func (m *CredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialRequest.Merge(m, src)
}
func (m *CredentialRequest) XXX_Size() int {
	return xxx_messageInfo_CredentialRequest.Size(m)
}
func (m *CredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialRequest proto.InternalMessageInfo

func (m *CredentialRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CredentialRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type CredentialReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content              []*KV    `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialReply) Reset()         { *m = CredentialReply{} }
func (m *CredentialReply) String() string { return proto.CompactTextString(m) }
func (*CredentialReply) ProtoMessage()    {}
func (*CredentialReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{8}
}
func (m *CredentialReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialReply.Unmarshal(m, b)
}
func (m *CredentialReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialReply.Marshal(b, m, deterministic)
}
func (m *CredentialReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialReply.Merge(m, src)
}
func (m *CredentialReply) XXX_Size() int {
	return xxx_messageInfo_CredentialReply.Size(m)
}
func (m *CredentialReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialReply.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialReply proto.InternalMessageInfo

func (m *CredentialReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CredentialReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CredentialReply) GetContent() []*KV {
	if m != nil {
		return m.Content
	}
	return nil
}

type SettingReply struct {
	Items                []*KV    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettingReply) Reset()         { *m = SettingReply{} }
func (m *SettingReply) String() string { return proto.CompactTextString(m) }
func (*SettingReply) ProtoMessage()    {}
func (*SettingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{9}
}
func (m *SettingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingReply.Unmarshal(m, b)
}
func (m *SettingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingReply.Marshal(b, m, deterministic)
}
func (m *SettingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingReply.Merge(m, src)
}
func (m *SettingReply) XXX_Size() int {
	return xxx_messageInfo_SettingReply.Size(m)
}
func (m *SettingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingReply.DiscardUnknown(m)
}

var xxx_messageInfo_SettingReply proto.InternalMessageInfo

func (m *SettingReply) GetItems() []*KV {
	if m != nil {
		return m.Items
	}
	return nil
}

type Script struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Script) Reset()         { *m = Script{} }
func (m *Script) String() string { return proto.CompactTextString(m) }
func (*Script) ProtoMessage()    {}
func (*Script) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{10}
}
func (m *Script) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Script.Unmarshal(m, b)
}
func (m *Script) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Script.Marshal(b, m, deterministic)
}
func (m *Script) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Script.Merge(m, src)
}
func (m *Script) XXX_Size() int {
	return xxx_messageInfo_Script.Size(m)
}
func (m *Script) XXX_DiscardUnknown() {
	xxx_messageInfo_Script.DiscardUnknown(m)
}

var xxx_messageInfo_Script proto.InternalMessageInfo

func (m *Script) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Script) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ScriptsReply struct {
	Items                []*Script `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScriptsReply) Reset()         { *m = ScriptsReply{} }
func (m *ScriptsReply) String() string { return proto.CompactTextString(m) }
func (*ScriptsReply) ProtoMessage()    {}
func (*ScriptsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{11}
}
func (m *ScriptsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScriptsReply.Unmarshal(m, b)
}
func (m *ScriptsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScriptsReply.Marshal(b, m, deterministic)
}
func (m *ScriptsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScriptsReply.Merge(m, src)
}
func (m *ScriptsReply) XXX_Size() int {
	return xxx_messageInfo_ScriptsReply.Size(m)
}
func (m *ScriptsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ScriptsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ScriptsReply proto.InternalMessageInfo

func (m *ScriptsReply) GetItems() []*Script {
	if m != nil {
		return m.Items
	}
	return nil
}

type Action struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{12}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Action) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ActionReply struct {
	Items                []*Action `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ActionReply) Reset()         { *m = ActionReply{} }
func (m *ActionReply) String() string { return proto.CompactTextString(m) }
func (*ActionReply) ProtoMessage()    {}
func (*ActionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{13}
}
func (m *ActionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionReply.Unmarshal(m, b)
}
func (m *ActionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionReply.Marshal(b, m, deterministic)
}
func (m *ActionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionReply.Merge(m, src)
}
func (m *ActionReply) XXX_Size() int {
	return xxx_messageInfo_ActionReply.Size(m)
}
func (m *ActionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ActionReply proto.InternalMessageInfo

func (m *ActionReply) GetItems() []*Action {
	if m != nil {
		return m.Items
	}
	return nil
}

type KVRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVRequest) Reset()         { *m = KVRequest{} }
func (m *KVRequest) String() string { return proto.CompactTextString(m) }
func (*KVRequest) ProtoMessage()    {}
func (*KVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{14}
}
func (m *KVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVRequest.Unmarshal(m, b)
}
func (m *KVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVRequest.Marshal(b, m, deterministic)
}
func (m *KVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVRequest.Merge(m, src)
}
func (m *KVRequest) XXX_Size() int {
	return xxx_messageInfo_KVRequest.Size(m)
}
func (m *KVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KVRequest proto.InternalMessageInfo

func (m *KVRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KVsRequest struct {
	Kvs                  []*KV    `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVsRequest) Reset()         { *m = KVsRequest{} }
func (m *KVsRequest) String() string { return proto.CompactTextString(m) }
func (*KVsRequest) ProtoMessage()    {}
func (*KVsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{15}
}
func (m *KVsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVsRequest.Unmarshal(m, b)
}
func (m *KVsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVsRequest.Marshal(b, m, deterministic)
}
func (m *KVsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVsRequest.Merge(m, src)
}
func (m *KVsRequest) XXX_Size() int {
	return xxx_messageInfo_KVsRequest.Size(m)
}
func (m *KVsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KVsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KVsRequest proto.InternalMessageInfo

func (m *KVsRequest) GetKvs() []*KV {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type KV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_492fc6d32fb115aa, []int{16}
}
func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*PageRequest)(nil), "pb.PageRequest")
	proto.RegisterType((*PageReply)(nil), "pb.PageReply")
	proto.RegisterType((*AppRequest)(nil), "pb.AppRequest")
	proto.RegisterType((*AppsReply)(nil), "pb.AppsReply")
	proto.RegisterType((*AppReply)(nil), "pb.AppReply")
	proto.RegisterType((*App)(nil), "pb.App")
	proto.RegisterType((*CredentialsReply)(nil), "pb.CredentialsReply")
	proto.RegisterType((*CredentialRequest)(nil), "pb.CredentialRequest")
	proto.RegisterType((*CredentialReply)(nil), "pb.CredentialReply")
	proto.RegisterType((*SettingReply)(nil), "pb.SettingReply")
	proto.RegisterType((*Script)(nil), "pb.Script")
	proto.RegisterType((*ScriptsReply)(nil), "pb.ScriptsReply")
	proto.RegisterType((*Action)(nil), "pb.Action")
	proto.RegisterType((*ActionReply)(nil), "pb.ActionReply")
	proto.RegisterType((*KVRequest)(nil), "pb.KVRequest")
	proto.RegisterType((*KVsRequest)(nil), "pb.KVsRequest")
	proto.RegisterType((*KV)(nil), "pb.KV")
}

func init() { proto.RegisterFile("middle.proto", fileDescriptor_492fc6d32fb115aa) }

var fileDescriptor_492fc6d32fb115aa = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0x05, 0x4c, 0x48, 0x98, 0xf0, 0x27, 0xbf, 0xfd, 0xa5, 0x92, 0x95, 0xe6, 0x80, 0xf6, 0x10,
	0x21, 0x35, 0x22, 0x09, 0xe9, 0xa5, 0xaa, 0x7a, 0xa0, 0x39, 0x70, 0x40, 0x51, 0x1a, 0xa8, 0x38,
	0xb4, 0x97, 0x2e, 0x61, 0x9a, 0x5a, 0x71, 0xec, 0xad, 0x3d, 0x44, 0xd0, 0x0f, 0xdb, 0xcf, 0x52,
	0xed, 0x1f, 0x1b, 0x83, 0x45, 0x4b, 0xd4, 0xde, 0x76, 0x86, 0x79, 0xef, 0xcd, 0x8e, 0xe7, 0x2d,
	0x50, 0x7b, 0xf4, 0xa6, 0x53, 0x1f, 0x3b, 0x32, 0x0a, 0x29, 0x64, 0x25, 0x39, 0x39, 0x82, 0x89,
	0x88, 0x6d, 0xcc, 0x6f, 0x61, 0xff, 0x83, 0xb8, 0xc7, 0x21, 0x7e, 0x9f, 0x61, 0x4c, 0x8c, 0x41,
	0x79, 0x36, 0xf3, 0xa6, 0x6e, 0xb1, 0x55, 0x6c, 0x57, 0x87, 0xfa, 0xcc, 0x0e, 0x61, 0x87, 0x3c,
	0xf2, 0xd1, 0x2d, 0xe9, 0xa4, 0x09, 0x98, 0x0b, 0xbb, 0x77, 0x61, 0x40, 0x18, 0x90, 0xeb, 0xe8,
	0x7c, 0x12, 0xf2, 0x1b, 0xa8, 0x1a, 0x4a, 0xe9, 0x2f, 0xfe, 0x09, 0xe1, 0x17, 0x80, 0x9e, 0x94,
	0x99, 0x16, 0x03, 0xf1, 0x88, 0x09, 0xa3, 0x3a, 0xab, 0x1c, 0x2d, 0x64, 0x42, 0xa8, 0xcf, 0x5a,
	0x25, 0x7c, 0xc0, 0xc0, 0xb2, 0x99, 0x40, 0x65, 0x71, 0x4e, 0x91, 0x70, 0xcb, 0x26, 0xab, 0x03,
	0xde, 0x86, 0x6a, 0x4f, 0xca, 0xd8, 0xb4, 0xfc, 0x12, 0xca, 0x42, 0xca, 0xd8, 0x2d, 0xb6, 0x9c,
	0xf6, 0x7e, 0x77, 0xb7, 0x23, 0x27, 0x1d, 0x25, 0xaf, 0x93, 0xfc, 0x2b, 0xec, 0xe9, 0x5e, 0xec,
	0xdd, 0xfe, 0xa2, 0x93, 0xe3, 0x65, 0x27, 0x4a, 0xa7, 0xa2, 0x74, 0x06, 0xe3, 0xa4, 0xa3, 0x11,
	0x38, 0x3d, 0x29, 0x97, 0xa3, 0x2a, 0x66, 0x47, 0xc5, 0xa1, 0xe6, 0xc5, 0xbd, 0x19, 0x7d, 0x0b,
	0x23, 0xef, 0x07, 0x4e, 0xb5, 0xd8, 0xde, 0x70, 0x25, 0x97, 0x36, 0xe2, 0x2c, 0x1b, 0xe1, 0xe7,
	0x70, 0x70, 0x15, 0xe1, 0x14, 0x03, 0xf2, 0x84, 0x6f, 0x6f, 0x7b, 0x0c, 0x3b, 0x1e, 0xe1, 0x63,
	0x72, 0xdd, 0xb4, 0x0d, 0x9d, 0xe4, 0x6f, 0xe1, 0xbf, 0x25, 0xe2, 0x99, 0x5f, 0x80, 0x7f, 0x86,
	0x66, 0x16, 0xfc, 0x9c, 0x91, 0xb5, 0xb2, 0xcb, 0x90, 0xed, 0x2b, 0x5d, 0x8a, 0x53, 0xa8, 0x8d,
	0x90, 0xc8, 0x0b, 0xee, 0xb7, 0xb9, 0xc7, 0x29, 0x54, 0x46, 0x77, 0x91, 0x27, 0x89, 0x35, 0xa0,
	0x64, 0xd7, 0xd1, 0x19, 0x96, 0x3c, 0x33, 0x27, 0x9c, 0x53, 0xaa, 0x8e, 0x73, 0xe2, 0xe7, 0x50,
	0x33, 0xd5, 0x76, 0x46, 0xad, 0x55, 0x6e, 0x50, 0xdc, 0xa6, 0x20, 0xc3, 0xdf, 0xbb, 0x23, 0x2f,
	0x0c, 0xb6, 0xe2, 0x3f, 0x83, 0x7d, 0x53, 0xbd, 0x99, 0xde, 0xfe, 0x6e, 0xe9, 0x2f, 0xa1, 0x3a,
	0x18, 0x27, 0xe3, 0x3f, 0x00, 0xe7, 0x01, 0x17, 0x76, 0x84, 0xea, 0xa8, 0xb6, 0xe4, 0x49, 0xf8,
	0xb3, 0xd4, 0x50, 0x3a, 0xe0, 0x27, 0x00, 0x83, 0x71, 0x9c, 0xa0, 0x5c, 0x70, 0x1e, 0x9e, 0xd6,
	0xa7, 0xa3, 0x52, 0xfc, 0x14, 0x4a, 0x83, 0xf1, 0xb6, 0xac, 0xdd, 0x9f, 0x15, 0xa8, 0x5c, 0xeb,
	0x17, 0x85, 0x75, 0x00, 0xae, 0x22, 0x14, 0x84, 0xca, 0xee, 0xac, 0xa9, 0x38, 0x33, 0x6f, 0xc9,
	0x51, 0x5d, 0x25, 0x3e, 0xe2, 0x9c, 0xf4, 0x2d, 0x79, 0x81, 0xbd, 0x82, 0xdd, 0x3e, 0xd2, 0x6f,
	0x8a, 0xd3, 0x67, 0x83, 0x17, 0xd8, 0x09, 0x94, 0x6e, 0x23, 0x53, 0x67, 0x38, 0x36, 0x90, 0xb6,
	0xa1, 0xac, 0xac, 0xbb, 0xa1, 0x32, 0x75, 0x35, 0x2f, 0xb0, 0x2e, 0x34, 0xfb, 0x48, 0xbd, 0x27,
	0xe1, 0xf9, 0x62, 0xe2, 0xa3, 0xb2, 0x57, 0x0e, 0x54, 0x4b, 0xdc, 0x6e, 0x31, 0x17, 0x50, 0x1f,
	0x51, 0x18, 0xa9, 0xe2, 0x1b, 0x65, 0x2e, 0xd6, 0x48, 0x0b, 0x0c, 0x40, 0xc7, 0x23, 0x12, 0x94,
	0x36, 0xfe, 0x06, 0x1a, 0x7d, 0xa4, 0x8c, 0xcf, 0xf2, 0x2a, 0x87, 0x2a, 0xb1, 0xee, 0x44, 0x5e,
	0x60, 0xef, 0xa0, 0xbe, 0x02, 0x65, 0x2f, 0x56, 0x0b, 0x13, 0xfc, 0xff, 0xeb, 0x69, 0x03, 0x7f,
	0xad, 0xed, 0x2d, 0x08, 0x33, 0x0c, 0x0d, 0xf3, 0xa5, 0xe3, 0xcd, 0xfd, 0x5e, 0x00, 0xf4, 0x91,
	0xac, 0x97, 0xf2, 0xbd, 0x1e, 0x68, 0x40, 0xc6, 0x69, 0xbc, 0xc0, 0xce, 0xa1, 0x6e, 0x84, 0x12,
	0x54, 0xdd, 0xee, 0xd3, 0x9f, 0x44, 0x8c, 0xa9, 0x36, 0x89, 0x64, 0x2c, 0xa7, 0x21, 0x35, 0x2b,
	0x62, 0x8c, 0x9b, 0x03, 0xe5, 0x55, 0xce, 0xa0, 0xaa, 0xbe, 0xb0, 0x31, 0x62, 0xae, 0xbe, 0x99,
	0xf1, 0xd5, 0xba, 0xc6, 0x26, 0x4c, 0x5e, 0xc3, 0x2c, 0xf1, 0x35, 0x06, 0xb3, 0x2d, 0x96, 0xb3,
	0x0b, 0xf5, 0xe4, 0x49, 0x16, 0x5b, 0x0a, 0xbc, 0xdf, 0xfb, 0x54, 0x11, 0xd2, 0x3b, 0x93, 0x93,
	0x49, 0x45, 0xff, 0x45, 0x5f, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x57, 0xbf, 0x86, 0x81, 0xc2,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MiddleClient is the client API for Middle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiddleClient interface {
	CreatePage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*TextReply, error)
	GetPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageReply, error)
	Qr(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextReply, error)
	Apps(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*AppsReply, error)
	GetAvailableApp(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*AppReply, error)
	StoreAppOAuth(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*StateReply, error)
	GetCredentials(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*CredentialsReply, error)
	GetCredential(ctx context.Context, in *CredentialRequest, opts ...grpc.CallOption) (*CredentialReply, error)
	CreateCredential(ctx context.Context, in *KVsRequest, opts ...grpc.CallOption) (*StateReply, error)
	GetSetting(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*SettingReply, error)
	CreateSetting(ctx context.Context, in *KVRequest, opts ...grpc.CallOption) (*StateReply, error)
	GetScripts(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*ScriptsReply, error)
	CreateScript(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*StateReply, error)
	GetAction(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*ActionReply, error)
	CreateAction(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*StateReply, error)
	GetMenu(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextReply, error)
	Authorization(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*StateReply, error)
}

type middleClient struct {
	cc *grpc.ClientConn
}

func NewMiddleClient(cc *grpc.ClientConn) MiddleClient {
	return &middleClient{cc}
}

func (c *middleClient) CreatePage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*TextReply, error) {
	out := new(TextReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/CreatePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) GetPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageReply, error) {
	out := new(PageReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) Qr(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextReply, error) {
	out := new(TextReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/Qr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) Apps(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*AppsReply, error) {
	out := new(AppsReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/Apps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) GetAvailableApp(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*AppReply, error) {
	out := new(AppReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/GetAvailableApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) StoreAppOAuth(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/StoreAppOAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) GetCredentials(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*CredentialsReply, error) {
	out := new(CredentialsReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/GetCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) GetCredential(ctx context.Context, in *CredentialRequest, opts ...grpc.CallOption) (*CredentialReply, error) {
	out := new(CredentialReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/GetCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) CreateCredential(ctx context.Context, in *KVsRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/CreateCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) GetSetting(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*SettingReply, error) {
	out := new(SettingReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/GetSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) CreateSetting(ctx context.Context, in *KVRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/CreateSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) GetScripts(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*ScriptsReply, error) {
	out := new(ScriptsReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/GetScripts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) CreateScript(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/CreateScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) GetAction(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*ActionReply, error) {
	out := new(ActionReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/GetAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) CreateAction(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/CreateAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) GetMenu(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextReply, error) {
	out := new(TextReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/GetMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middleClient) Authorization(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Middle/Authorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddleServer is the server API for Middle service.
type MiddleServer interface {
	CreatePage(context.Context, *PageRequest) (*TextReply, error)
	GetPage(context.Context, *PageRequest) (*PageReply, error)
	Qr(context.Context, *TextRequest) (*TextReply, error)
	Apps(context.Context, *TextRequest) (*AppsReply, error)
	GetAvailableApp(context.Context, *TextRequest) (*AppReply, error)
	StoreAppOAuth(context.Context, *AppRequest) (*StateReply, error)
	GetCredentials(context.Context, *TextRequest) (*CredentialsReply, error)
	GetCredential(context.Context, *CredentialRequest) (*CredentialReply, error)
	CreateCredential(context.Context, *KVsRequest) (*StateReply, error)
	GetSetting(context.Context, *TextRequest) (*SettingReply, error)
	CreateSetting(context.Context, *KVRequest) (*StateReply, error)
	GetScripts(context.Context, *TextRequest) (*ScriptsReply, error)
	CreateScript(context.Context, *TextRequest) (*StateReply, error)
	GetAction(context.Context, *TextRequest) (*ActionReply, error)
	CreateAction(context.Context, *TextRequest) (*StateReply, error)
	GetMenu(context.Context, *TextRequest) (*TextReply, error)
	Authorization(context.Context, *TextRequest) (*StateReply, error)
}

// UnimplementedMiddleServer can be embedded to have forward compatible implementations.
type UnimplementedMiddleServer struct {
}

func (*UnimplementedMiddleServer) CreatePage(ctx context.Context, req *PageRequest) (*TextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePage not implemented")
}
func (*UnimplementedMiddleServer) GetPage(ctx context.Context, req *PageRequest) (*PageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (*UnimplementedMiddleServer) Qr(ctx context.Context, req *TextRequest) (*TextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Qr not implemented")
}
func (*UnimplementedMiddleServer) Apps(ctx context.Context, req *TextRequest) (*AppsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apps not implemented")
}
func (*UnimplementedMiddleServer) GetAvailableApp(ctx context.Context, req *TextRequest) (*AppReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableApp not implemented")
}
func (*UnimplementedMiddleServer) StoreAppOAuth(ctx context.Context, req *AppRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreAppOAuth not implemented")
}
func (*UnimplementedMiddleServer) GetCredentials(ctx context.Context, req *TextRequest) (*CredentialsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredentials not implemented")
}
func (*UnimplementedMiddleServer) GetCredential(ctx context.Context, req *CredentialRequest) (*CredentialReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredential not implemented")
}
func (*UnimplementedMiddleServer) CreateCredential(ctx context.Context, req *KVsRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCredential not implemented")
}
func (*UnimplementedMiddleServer) GetSetting(ctx context.Context, req *TextRequest) (*SettingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSetting not implemented")
}
func (*UnimplementedMiddleServer) CreateSetting(ctx context.Context, req *KVRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSetting not implemented")
}
func (*UnimplementedMiddleServer) GetScripts(ctx context.Context, req *TextRequest) (*ScriptsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScripts not implemented")
}
func (*UnimplementedMiddleServer) CreateScript(ctx context.Context, req *TextRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScript not implemented")
}
func (*UnimplementedMiddleServer) GetAction(ctx context.Context, req *TextRequest) (*ActionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAction not implemented")
}
func (*UnimplementedMiddleServer) CreateAction(ctx context.Context, req *TextRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAction not implemented")
}
func (*UnimplementedMiddleServer) GetMenu(ctx context.Context, req *TextRequest) (*TextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenu not implemented")
}
func (*UnimplementedMiddleServer) Authorization(ctx context.Context, req *TextRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorization not implemented")
}

func RegisterMiddleServer(s *grpc.Server, srv MiddleServer) {
	s.RegisterService(&_Middle_serviceDesc, srv)
}

func _Middle_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/CreatePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).CreatePage(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).GetPage(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_Qr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).Qr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/Qr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).Qr(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_Apps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).Apps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/Apps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).Apps(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_GetAvailableApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).GetAvailableApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/GetAvailableApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).GetAvailableApp(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_StoreAppOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).StoreAppOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/StoreAppOAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).StoreAppOAuth(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/GetCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).GetCredentials(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_GetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).GetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/GetCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).GetCredential(ctx, req.(*CredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_CreateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).CreateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/CreateCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).CreateCredential(ctx, req.(*KVsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_GetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).GetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/GetSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).GetSetting(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_CreateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).CreateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/CreateSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).CreateSetting(ctx, req.(*KVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_GetScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).GetScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/GetScripts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).GetScripts(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_CreateScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).CreateScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/CreateScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).CreateScript(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_GetAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).GetAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/GetAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).GetAction(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_CreateAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).CreateAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/CreateAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).CreateAction(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/GetMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).GetMenu(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middle_Authorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).Authorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Middle/Authorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).Authorization(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Middle_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Middle",
	HandlerType: (*MiddleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _Middle_CreatePage_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _Middle_GetPage_Handler,
		},
		{
			MethodName: "Qr",
			Handler:    _Middle_Qr_Handler,
		},
		{
			MethodName: "Apps",
			Handler:    _Middle_Apps_Handler,
		},
		{
			MethodName: "GetAvailableApp",
			Handler:    _Middle_GetAvailableApp_Handler,
		},
		{
			MethodName: "StoreAppOAuth",
			Handler:    _Middle_StoreAppOAuth_Handler,
		},
		{
			MethodName: "GetCredentials",
			Handler:    _Middle_GetCredentials_Handler,
		},
		{
			MethodName: "GetCredential",
			Handler:    _Middle_GetCredential_Handler,
		},
		{
			MethodName: "CreateCredential",
			Handler:    _Middle_CreateCredential_Handler,
		},
		{
			MethodName: "GetSetting",
			Handler:    _Middle_GetSetting_Handler,
		},
		{
			MethodName: "CreateSetting",
			Handler:    _Middle_CreateSetting_Handler,
		},
		{
			MethodName: "GetScripts",
			Handler:    _Middle_GetScripts_Handler,
		},
		{
			MethodName: "CreateScript",
			Handler:    _Middle_CreateScript_Handler,
		},
		{
			MethodName: "GetAction",
			Handler:    _Middle_GetAction_Handler,
		},
		{
			MethodName: "CreateAction",
			Handler:    _Middle_CreateAction_Handler,
		},
		{
			MethodName: "GetMenu",
			Handler:    _Middle_GetMenu_Handler,
		},
		{
			MethodName: "Authorization",
			Handler:    _Middle_Authorization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "middle.proto",
}
