// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: org.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Objective struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" db:"name"`
	// @inject_tag: db:"tag_id"
	TagId int64 `protobuf:"varint,4,opt,name=tagId,proto3" json:"tagId,omitempty" db:"tag_id"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" db:"updated_at"`
}

func (m *Objective) Reset()         { *m = Objective{} }
func (m *Objective) String() string { return proto.CompactTextString(m) }
func (*Objective) ProtoMessage()    {}
func (*Objective) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{0}
}
func (m *Objective) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Objective) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Objective.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Objective) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Objective.Merge(m, src)
}
func (m *Objective) XXX_Size() int {
	return m.Size()
}
func (m *Objective) XXX_DiscardUnknown() {
	xxx_messageInfo_Objective.DiscardUnknown(m)
}

var xxx_messageInfo_Objective proto.InternalMessageInfo

func (m *Objective) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Objective) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Objective) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *Objective) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Objective) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type KeyResult struct {
	// @inject_tag: db:"id" gorm:"primaryKey"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" gorm:"primaryKey"`
	// @inject_tag: db:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" db:"name"`
	// @inject_tag: db:"objective_id"
	ObjectiveId int64 `protobuf:"varint,3,opt,name=objectiveId,proto3" json:"objectiveId,omitempty" db:"objective_id"`
	// @inject_tag: db:"tag_id"
	TagId int64 `protobuf:"varint,5,opt,name=tagId,proto3" json:"tagId,omitempty" db:"tag_id"`
	// @inject_tag: db:"complete"
	Complete bool `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty" db:"complete"`
	// @inject_tag: db:"created_at"
	CreatedAt int64 `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt int64 `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" db:"updated_at"`
}

func (m *KeyResult) Reset()         { *m = KeyResult{} }
func (m *KeyResult) String() string { return proto.CompactTextString(m) }
func (*KeyResult) ProtoMessage()    {}
func (*KeyResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{1}
}
func (m *KeyResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyResult.Merge(m, src)
}
func (m *KeyResult) XXX_Size() int {
	return m.Size()
}
func (m *KeyResult) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyResult.DiscardUnknown(m)
}

var xxx_messageInfo_KeyResult proto.InternalMessageInfo

func (m *KeyResult) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KeyResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeyResult) GetObjectiveId() int64 {
	if m != nil {
		return m.ObjectiveId
	}
	return 0
}

func (m *KeyResult) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *KeyResult) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func (m *KeyResult) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *KeyResult) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type ObjectiveRequest struct {
	Objective *Objective `protobuf:"bytes,1,opt,name=objective,proto3" json:"objective,omitempty"`
}

func (m *ObjectiveRequest) Reset()         { *m = ObjectiveRequest{} }
func (m *ObjectiveRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectiveRequest) ProtoMessage()    {}
func (*ObjectiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{2}
}
func (m *ObjectiveRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectiveRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectiveRequest.Merge(m, src)
}
func (m *ObjectiveRequest) XXX_Size() int {
	return m.Size()
}
func (m *ObjectiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectiveRequest proto.InternalMessageInfo

func (m *ObjectiveRequest) GetObjective() *Objective {
	if m != nil {
		return m.Objective
	}
	return nil
}

type ObjectiveReply struct {
	Objective *Objective `protobuf:"bytes,1,opt,name=objective,proto3" json:"objective,omitempty"`
}

func (m *ObjectiveReply) Reset()         { *m = ObjectiveReply{} }
func (m *ObjectiveReply) String() string { return proto.CompactTextString(m) }
func (*ObjectiveReply) ProtoMessage()    {}
func (*ObjectiveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{3}
}
func (m *ObjectiveReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectiveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectiveReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectiveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectiveReply.Merge(m, src)
}
func (m *ObjectiveReply) XXX_Size() int {
	return m.Size()
}
func (m *ObjectiveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectiveReply.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectiveReply proto.InternalMessageInfo

func (m *ObjectiveReply) GetObjective() *Objective {
	if m != nil {
		return m.Objective
	}
	return nil
}

type ObjectivesReply struct {
	Objective []*Objective `protobuf:"bytes,1,rep,name=objective,proto3" json:"objective,omitempty"`
}

func (m *ObjectivesReply) Reset()         { *m = ObjectivesReply{} }
func (m *ObjectivesReply) String() string { return proto.CompactTextString(m) }
func (*ObjectivesReply) ProtoMessage()    {}
func (*ObjectivesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{4}
}
func (m *ObjectivesReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectivesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectivesReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectivesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectivesReply.Merge(m, src)
}
func (m *ObjectivesReply) XXX_Size() int {
	return m.Size()
}
func (m *ObjectivesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectivesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectivesReply proto.InternalMessageInfo

func (m *ObjectivesReply) GetObjective() []*Objective {
	if m != nil {
		return m.Objective
	}
	return nil
}

type KeyResultRequest struct {
	KeyResult *KeyResult `protobuf:"bytes,1,opt,name=keyResult,proto3" json:"keyResult,omitempty"`
}

func (m *KeyResultRequest) Reset()         { *m = KeyResultRequest{} }
func (m *KeyResultRequest) String() string { return proto.CompactTextString(m) }
func (*KeyResultRequest) ProtoMessage()    {}
func (*KeyResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{5}
}
func (m *KeyResultRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyResultRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyResultRequest.Merge(m, src)
}
func (m *KeyResultRequest) XXX_Size() int {
	return m.Size()
}
func (m *KeyResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyResultRequest proto.InternalMessageInfo

func (m *KeyResultRequest) GetKeyResult() *KeyResult {
	if m != nil {
		return m.KeyResult
	}
	return nil
}

type KeyResultReply struct {
	KeyResult *KeyResult `protobuf:"bytes,1,opt,name=keyResult,proto3" json:"keyResult,omitempty"`
}

func (m *KeyResultReply) Reset()         { *m = KeyResultReply{} }
func (m *KeyResultReply) String() string { return proto.CompactTextString(m) }
func (*KeyResultReply) ProtoMessage()    {}
func (*KeyResultReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{6}
}
func (m *KeyResultReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyResultReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyResultReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyResultReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyResultReply.Merge(m, src)
}
func (m *KeyResultReply) XXX_Size() int {
	return m.Size()
}
func (m *KeyResultReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyResultReply.DiscardUnknown(m)
}

var xxx_messageInfo_KeyResultReply proto.InternalMessageInfo

func (m *KeyResultReply) GetKeyResult() *KeyResult {
	if m != nil {
		return m.KeyResult
	}
	return nil
}

type KeyResultsReply struct {
	Result []*KeyResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (m *KeyResultsReply) Reset()         { *m = KeyResultsReply{} }
func (m *KeyResultsReply) String() string { return proto.CompactTextString(m) }
func (*KeyResultsReply) ProtoMessage()    {}
func (*KeyResultsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{7}
}
func (m *KeyResultsReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyResultsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyResultsReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyResultsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyResultsReply.Merge(m, src)
}
func (m *KeyResultsReply) XXX_Size() int {
	return m.Size()
}
func (m *KeyResultsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyResultsReply.DiscardUnknown(m)
}

var xxx_messageInfo_KeyResultsReply proto.InternalMessageInfo

func (m *KeyResultsReply) GetResult() []*KeyResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Objective)(nil), "pb.Objective")
	proto.RegisterType((*KeyResult)(nil), "pb.KeyResult")
	proto.RegisterType((*ObjectiveRequest)(nil), "pb.ObjectiveRequest")
	proto.RegisterType((*ObjectiveReply)(nil), "pb.ObjectiveReply")
	proto.RegisterType((*ObjectivesReply)(nil), "pb.ObjectivesReply")
	proto.RegisterType((*KeyResultRequest)(nil), "pb.KeyResultRequest")
	proto.RegisterType((*KeyResultReply)(nil), "pb.KeyResultReply")
	proto.RegisterType((*KeyResultsReply)(nil), "pb.KeyResultsReply")
}

func init() { proto.RegisterFile("org.proto", fileDescriptor_ccb462779e28924f) }

var fileDescriptor_ccb462779e28924f = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4d, 0x6f, 0xd3, 0x30,
	0x1c, 0xc6, 0xe3, 0x66, 0x0d, 0xcd, 0x7f, 0xac, 0x9d, 0xbc, 0x1e, 0xa2, 0x0a, 0x59, 0x55, 0x24,
	0xa4, 0x4a, 0xa0, 0x4e, 0x1a, 0x17, 0x86, 0x80, 0x89, 0x17, 0x09, 0x4d, 0x1c, 0x26, 0x65, 0x37,
	0x6e, 0x79, 0xb1, 0xa2, 0x40, 0x47, 0x4c, 0xe2, 0x4e, 0xda, 0x91, 0x6f, 0xc0, 0x91, 0x6f, 0xc3,
	0x75, 0xc7, 0x1e, 0x39, 0xb2, 0xe6, 0xc2, 0xc7, 0x40, 0x71, 0x12, 0xdb, 0xd9, 0xd8, 0xba, 0xdc,
	0xec, 0xe7, 0xf9, 0xff, 0xd2, 0xe7, 0xb1, 0xd3, 0x80, 0x9d, 0x66, 0xf1, 0x9c, 0x65, 0x29, 0x4f,
	0x71, 0x8f, 0x05, 0x13, 0x08, 0xfc, 0x9c, 0x56, 0xfb, 0xc9, 0x38, 0x4e, 0xe3, 0x54, 0x2c, 0xf7,
	0xcb, 0x55, 0xa5, 0xba, 0xdf, 0x11, 0xd8, 0x27, 0xc1, 0x67, 0x1a, 0xf2, 0xe4, 0x9c, 0xe2, 0x21,
	0xf4, 0x92, 0xc8, 0x41, 0x53, 0x34, 0x33, 0xbd, 0x5e, 0x12, 0x61, 0x0c, 0x5b, 0x5f, 0xfd, 0x33,
	0xea, 0xf4, 0xa6, 0x68, 0x66, 0x7b, 0x62, 0x8d, 0xc7, 0xd0, 0xe7, 0x7e, 0x7c, 0x1c, 0x39, 0x5b,
	0x62, 0xac, 0xda, 0xe0, 0x47, 0x60, 0x87, 0x19, 0xf5, 0x39, 0x8d, 0xde, 0x70, 0xa7, 0x2f, 0x1c,
	0x25, 0x94, 0xee, 0x92, 0x45, 0xb5, 0x3b, 0xa8, 0x5c, 0x29, 0xb8, 0xbf, 0x10, 0xd8, 0x1f, 0xe9,
	0x85, 0x47, 0xf3, 0xe5, 0x82, 0xdf, 0x2b, 0xc3, 0x14, 0xb6, 0xd3, 0x26, 0xf4, 0x71, 0xe4, 0x98,
	0x62, 0x58, 0x97, 0x54, 0xca, 0xbe, 0x9e, 0x72, 0x02, 0x83, 0x30, 0x3d, 0x63, 0x0b, 0xca, 0xa9,
	0x63, 0x4d, 0xd1, 0x6c, 0xe0, 0xc9, 0x7d, 0xbb, 0xc1, 0x83, 0x6e, 0x0d, 0x8e, 0x60, 0x57, 0x1e,
	0xa2, 0x47, 0xbf, 0x2d, 0x69, 0xce, 0xf1, 0x13, 0xb0, 0x65, 0x20, 0x51, 0x67, 0xfb, 0x60, 0x67,
	0xce, 0x82, 0xb9, 0x1a, 0x54, 0xbe, 0xfb, 0x0a, 0x86, 0xda, 0x03, 0xd8, 0xe2, 0xa2, 0x1b, 0xfe,
	0x1a, 0x46, 0x52, 0xcf, 0xff, 0xcb, 0x9b, 0x77, 0xf2, 0x47, 0xb0, 0x2b, 0x2f, 0x40, 0xcb, 0xff,
	0xa5, 0xd1, 0xf4, 0x00, 0x6a, 0x50, 0xf9, 0x65, 0x7e, 0xed, 0x01, 0xf5, 0xef, 0xdf, 0x1f, 0x7f,
	0x0e, 0x23, 0xa9, 0xd7, 0xf9, 0x1f, 0x83, 0x95, 0x35, 0xb0, 0x79, 0x13, 0xae, 0xcd, 0x83, 0xbf,
	0x26, 0x58, 0x27, 0x59, 0x7c, 0x7a, 0x1e, 0xe2, 0x43, 0x18, 0xbd, 0x13, 0xf7, 0xa5, 0xde, 0xe7,
	0x71, 0xbb, 0x71, 0xd5, 0x6c, 0x32, 0x2c, 0xd5, 0x53, 0xee, 0xf3, 0xea, 0xa8, 0x5d, 0x03, 0xbf,
	0x80, 0x87, 0x1f, 0x28, 0xdf, 0xc4, 0xe1, 0x6b, 0x6a, 0xc5, 0xbe, 0x84, 0x1d, 0x9d, 0xcd, 0x6f,
	0x81, 0xf7, 0x5a, 0x6a, 0xde, 0xd0, 0x87, 0x30, 0x7a, 0x4f, 0xcb, 0xf7, 0xaf, 0x7b, 0x68, 0xd9,
	0x57, 0xfd, 0x77, 0xc6, 0xed, 0x43, 0xda, 0xd0, 0x77, 0x13, 0x87, 0xaf, 0xa9, 0x7a, 0x5f, 0x75,
	0x5d, 0xb7, 0xc0, 0x7b, 0x2d, 0xf5, 0x66, 0xdf, 0xce, 0xa1, 0xdf, 0x3e, 0xbd, 0xbc, 0x22, 0x68,
	0x75, 0x45, 0x8c, 0xcb, 0x35, 0x41, 0xab, 0x35, 0x41, 0x7f, 0xd6, 0x04, 0xfd, 0x28, 0x88, 0xf1,
	0xb3, 0x20, 0xc6, 0xaa, 0x20, 0xc6, 0xef, 0x82, 0x18, 0x9f, 0x2c, 0x9f, 0x25, 0xfb, 0x2c, 0x08,
	0x2c, 0xf1, 0x7d, 0x7b, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x31, 0x71, 0x9c, 0x12, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrgSvcClient is the client API for OrgSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrgSvcClient interface {
	CreateObjective(ctx context.Context, in *ObjectiveRequest, opts ...grpc.CallOption) (*StateReply, error)
	GetObjective(ctx context.Context, in *ObjectiveRequest, opts ...grpc.CallOption) (*ObjectiveReply, error)
	GetObjectives(ctx context.Context, in *ObjectiveRequest, opts ...grpc.CallOption) (*ObjectivesReply, error)
	DeleteObjective(ctx context.Context, in *ObjectiveRequest, opts ...grpc.CallOption) (*StateReply, error)
	CreateKeyResult(ctx context.Context, in *KeyResultRequest, opts ...grpc.CallOption) (*StateReply, error)
	GetKeyResult(ctx context.Context, in *KeyResultRequest, opts ...grpc.CallOption) (*KeyResultReply, error)
	GetKeyResults(ctx context.Context, in *KeyResultRequest, opts ...grpc.CallOption) (*KeyResultsReply, error)
	DeleteKeyResult(ctx context.Context, in *KeyResultRequest, opts ...grpc.CallOption) (*StateReply, error)
}

type orgSvcClient struct {
	cc *grpc.ClientConn
}

func NewOrgSvcClient(cc *grpc.ClientConn) OrgSvcClient {
	return &orgSvcClient{cc}
}

func (c *orgSvcClient) CreateObjective(ctx context.Context, in *ObjectiveRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.OrgSvc/CreateObjective", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgSvcClient) GetObjective(ctx context.Context, in *ObjectiveRequest, opts ...grpc.CallOption) (*ObjectiveReply, error) {
	out := new(ObjectiveReply)
	err := c.cc.Invoke(ctx, "/pb.OrgSvc/GetObjective", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgSvcClient) GetObjectives(ctx context.Context, in *ObjectiveRequest, opts ...grpc.CallOption) (*ObjectivesReply, error) {
	out := new(ObjectivesReply)
	err := c.cc.Invoke(ctx, "/pb.OrgSvc/GetObjectives", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgSvcClient) DeleteObjective(ctx context.Context, in *ObjectiveRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.OrgSvc/DeleteObjective", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgSvcClient) CreateKeyResult(ctx context.Context, in *KeyResultRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.OrgSvc/CreateKeyResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgSvcClient) GetKeyResult(ctx context.Context, in *KeyResultRequest, opts ...grpc.CallOption) (*KeyResultReply, error) {
	out := new(KeyResultReply)
	err := c.cc.Invoke(ctx, "/pb.OrgSvc/GetKeyResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgSvcClient) GetKeyResults(ctx context.Context, in *KeyResultRequest, opts ...grpc.CallOption) (*KeyResultsReply, error) {
	out := new(KeyResultsReply)
	err := c.cc.Invoke(ctx, "/pb.OrgSvc/GetKeyResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgSvcClient) DeleteKeyResult(ctx context.Context, in *KeyResultRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.OrgSvc/DeleteKeyResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrgSvcServer is the server API for OrgSvc service.
type OrgSvcServer interface {
	CreateObjective(context.Context, *ObjectiveRequest) (*StateReply, error)
	GetObjective(context.Context, *ObjectiveRequest) (*ObjectiveReply, error)
	GetObjectives(context.Context, *ObjectiveRequest) (*ObjectivesReply, error)
	DeleteObjective(context.Context, *ObjectiveRequest) (*StateReply, error)
	CreateKeyResult(context.Context, *KeyResultRequest) (*StateReply, error)
	GetKeyResult(context.Context, *KeyResultRequest) (*KeyResultReply, error)
	GetKeyResults(context.Context, *KeyResultRequest) (*KeyResultsReply, error)
	DeleteKeyResult(context.Context, *KeyResultRequest) (*StateReply, error)
}

// UnimplementedOrgSvcServer can be embedded to have forward compatible implementations.
type UnimplementedOrgSvcServer struct {
}

func (*UnimplementedOrgSvcServer) CreateObjective(ctx context.Context, req *ObjectiveRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObjective not implemented")
}
func (*UnimplementedOrgSvcServer) GetObjective(ctx context.Context, req *ObjectiveRequest) (*ObjectiveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObjective not implemented")
}
func (*UnimplementedOrgSvcServer) GetObjectives(ctx context.Context, req *ObjectiveRequest) (*ObjectivesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObjectives not implemented")
}
func (*UnimplementedOrgSvcServer) DeleteObjective(ctx context.Context, req *ObjectiveRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObjective not implemented")
}
func (*UnimplementedOrgSvcServer) CreateKeyResult(ctx context.Context, req *KeyResultRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyResult not implemented")
}
func (*UnimplementedOrgSvcServer) GetKeyResult(ctx context.Context, req *KeyResultRequest) (*KeyResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyResult not implemented")
}
func (*UnimplementedOrgSvcServer) GetKeyResults(ctx context.Context, req *KeyResultRequest) (*KeyResultsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyResults not implemented")
}
func (*UnimplementedOrgSvcServer) DeleteKeyResult(ctx context.Context, req *KeyResultRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyResult not implemented")
}

func RegisterOrgSvcServer(s *grpc.Server, srv OrgSvcServer) {
	s.RegisterService(&_OrgSvc_serviceDesc, srv)
}

func _OrgSvc_CreateObjective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).CreateObjective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrgSvc/CreateObjective",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).CreateObjective(ctx, req.(*ObjectiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgSvc_GetObjective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).GetObjective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrgSvc/GetObjective",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).GetObjective(ctx, req.(*ObjectiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgSvc_GetObjectives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).GetObjectives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrgSvc/GetObjectives",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).GetObjectives(ctx, req.(*ObjectiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgSvc_DeleteObjective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).DeleteObjective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrgSvc/DeleteObjective",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).DeleteObjective(ctx, req.(*ObjectiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgSvc_CreateKeyResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).CreateKeyResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrgSvc/CreateKeyResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).CreateKeyResult(ctx, req.(*KeyResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgSvc_GetKeyResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).GetKeyResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrgSvc/GetKeyResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).GetKeyResult(ctx, req.(*KeyResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgSvc_GetKeyResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).GetKeyResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrgSvc/GetKeyResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).GetKeyResults(ctx, req.(*KeyResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgSvc_DeleteKeyResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).DeleteKeyResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrgSvc/DeleteKeyResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).DeleteKeyResult(ctx, req.(*KeyResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrgSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrgSvc",
	HandlerType: (*OrgSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObjective",
			Handler:    _OrgSvc_CreateObjective_Handler,
		},
		{
			MethodName: "GetObjective",
			Handler:    _OrgSvc_GetObjective_Handler,
		},
		{
			MethodName: "GetObjectives",
			Handler:    _OrgSvc_GetObjectives_Handler,
		},
		{
			MethodName: "DeleteObjective",
			Handler:    _OrgSvc_DeleteObjective_Handler,
		},
		{
			MethodName: "CreateKeyResult",
			Handler:    _OrgSvc_CreateKeyResult_Handler,
		},
		{
			MethodName: "GetKeyResult",
			Handler:    _OrgSvc_GetKeyResult_Handler,
		},
		{
			MethodName: "GetKeyResults",
			Handler:    _OrgSvc_GetKeyResults_Handler,
		},
		{
			MethodName: "DeleteKeyResult",
			Handler:    _OrgSvc_DeleteKeyResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "org.proto",
}

func (m *Objective) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Objective) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Objective) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.CreatedAt != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x28
	}
	if m.TagId != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.TagId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintOrg(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *KeyResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.CreatedAt != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x38
	}
	if m.Complete {
		i--
		if m.Complete {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.TagId != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.TagId))
		i--
		dAtA[i] = 0x28
	}
	if m.ObjectiveId != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.ObjectiveId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintOrg(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintOrg(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ObjectiveRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectiveRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectiveRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Objective != nil {
		{
			size, err := m.Objective.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOrg(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ObjectiveReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectiveReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectiveReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Objective != nil {
		{
			size, err := m.Objective.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOrg(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ObjectivesReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectivesReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectivesReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Objective) > 0 {
		for iNdEx := len(m.Objective) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Objective[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOrg(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *KeyResultRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyResultRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyResultRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KeyResult != nil {
		{
			size, err := m.KeyResult.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOrg(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KeyResultReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyResultReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyResultReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KeyResult != nil {
		{
			size, err := m.KeyResult.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOrg(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KeyResultsReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyResultsReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyResultsReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		for iNdEx := len(m.Result) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Result[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOrg(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintOrg(dAtA []byte, offset int, v uint64) int {
	offset -= sovOrg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Objective) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovOrg(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovOrg(uint64(l))
	}
	if m.TagId != 0 {
		n += 1 + sovOrg(uint64(m.TagId))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovOrg(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovOrg(uint64(m.UpdatedAt))
	}
	return n
}

func (m *KeyResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovOrg(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovOrg(uint64(l))
	}
	if m.ObjectiveId != 0 {
		n += 1 + sovOrg(uint64(m.ObjectiveId))
	}
	if m.TagId != 0 {
		n += 1 + sovOrg(uint64(m.TagId))
	}
	if m.Complete {
		n += 2
	}
	if m.CreatedAt != 0 {
		n += 1 + sovOrg(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovOrg(uint64(m.UpdatedAt))
	}
	return n
}

func (m *ObjectiveRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Objective != nil {
		l = m.Objective.Size()
		n += 1 + l + sovOrg(uint64(l))
	}
	return n
}

func (m *ObjectiveReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Objective != nil {
		l = m.Objective.Size()
		n += 1 + l + sovOrg(uint64(l))
	}
	return n
}

func (m *ObjectivesReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Objective) > 0 {
		for _, e := range m.Objective {
			l = e.Size()
			n += 1 + l + sovOrg(uint64(l))
		}
	}
	return n
}

func (m *KeyResultRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeyResult != nil {
		l = m.KeyResult.Size()
		n += 1 + l + sovOrg(uint64(l))
	}
	return n
}

func (m *KeyResultReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeyResult != nil {
		l = m.KeyResult.Size()
		n += 1 + l + sovOrg(uint64(l))
	}
	return n
}

func (m *KeyResultsReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Result) > 0 {
		for _, e := range m.Result {
			l = e.Size()
			n += 1 + l + sovOrg(uint64(l))
		}
	}
	return n
}

func sovOrg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOrg(x uint64) (n int) {
	return sovOrg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Objective) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Objective: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Objective: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TagId", wireType)
			}
			m.TagId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TagId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectiveId", wireType)
			}
			m.ObjectiveId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObjectiveId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TagId", wireType)
			}
			m.TagId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TagId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Complete", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Complete = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectiveRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectiveRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectiveRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Objective", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Objective == nil {
				m.Objective = &Objective{}
			}
			if err := m.Objective.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectiveReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectiveReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectiveReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Objective", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Objective == nil {
				m.Objective = &Objective{}
			}
			if err := m.Objective.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectivesReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectivesReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectivesReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Objective", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Objective = append(m.Objective, &Objective{})
			if err := m.Objective[len(m.Objective)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyResultRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyResultRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyResultRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyResult", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.KeyResult == nil {
				m.KeyResult = &KeyResult{}
			}
			if err := m.KeyResult.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyResultReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyResultReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyResultReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyResult", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.KeyResult == nil {
				m.KeyResult = &KeyResult{}
			}
			if err := m.KeyResult.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyResultsReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyResultsReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyResultsReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result, &KeyResult{})
			if err := m.Result[len(m.Result)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOrg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOrg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOrg
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOrg
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOrg
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOrg        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOrg          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOrg = fmt.Errorf("proto: unexpected end of group")
)
