// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: storage.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FileRequest struct {
	// Types that are valid to be assigned to Data:
	//	*FileRequest_Info
	//	*FileRequest_Chuck
	Data                 isFileRequest_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}
func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

type isFileRequest_Data interface {
	isFileRequest_Data()
}

type FileRequest_Info struct {
	Info *FileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof" json:"info,omitempty"`
}
type FileRequest_Chuck struct {
	Chuck []byte `protobuf:"bytes,2,opt,name=chuck,proto3,oneof" json:"chuck,omitempty"`
}

func (*FileRequest_Info) isFileRequest_Data()  {}
func (*FileRequest_Chuck) isFileRequest_Data() {}

func (m *FileRequest) GetData() isFileRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FileRequest) GetInfo() *FileInfo {
	if x, ok := m.GetData().(*FileRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (m *FileRequest) GetChuck() []byte {
	if x, ok := m.GetData().(*FileRequest_Chuck); ok {
		return x.Chuck
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FileRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FileRequest_Info)(nil),
		(*FileRequest_Chuck)(nil),
	}
}

type FileInfo struct {
	FileType             string   `protobuf:"bytes,1,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}
func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

type FileReply struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReply) Reset()         { *m = FileReply{} }
func (m *FileReply) String() string { return proto.CompactTextString(m) }
func (*FileReply) ProtoMessage()    {}
func (*FileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}
func (m *FileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReply.Unmarshal(m, b)
}
func (m *FileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReply.Marshal(b, m, deterministic)
}
func (m *FileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReply.Merge(m, src)
}
func (m *FileReply) XXX_Size() int {
	return xxx_messageInfo_FileReply.Size(m)
}
func (m *FileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReply.DiscardUnknown(m)
}

var xxx_messageInfo_FileReply proto.InternalMessageInfo

func (m *FileReply) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*FileRequest)(nil), "pb.FileRequest")
	proto.RegisterType((*FileInfo)(nil), "pb.FileInfo")
	proto.RegisterType((*FileReply)(nil), "pb.FileReply")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0xa1, 0x41, 0x02, 0x53, 0x1a, 0x93, 0x3d, 0x98, 0xa6, 0x1e, 0x6c, 0xb8, 0xc8, 0x09,
	0x9b, 0xfa, 0x0b, 0xec, 0xc1, 0xd4, 0x9b, 0xd2, 0x7a, 0xf1, 0x62, 0x76, 0xe9, 0x20, 0xc4, 0x4d,
	0x77, 0x2c, 0x83, 0x91, 0x7f, 0x6f, 0xd8, 0xa5, 0x31, 0xde, 0xf6, 0xbd, 0xb7, 0xdf, 0xcc, 0xcb,
	0xc0, 0xac, 0x65, 0x73, 0x92, 0x1f, 0x98, 0xd3, 0xc9, 0xb0, 0x11, 0x13, 0x52, 0x0b, 0x50, 0xb2,
	0x1d, 0x75, 0xfa, 0x02, 0xd3, 0xc7, 0x46, 0x63, 0x81, 0x5f, 0x1d, 0xb6, 0x2c, 0x52, 0x08, 0x9a,
	0x63, 0x65, 0xe6, 0xfe, 0xd2, 0xcf, 0xa6, 0xeb, 0x24, 0x27, 0x95, 0x0f, 0xf1, 0xd3, 0xb1, 0x32,
	0x5b, 0xaf, 0xb0, 0x99, 0xb8, 0x82, 0x8b, 0xb2, 0xee, 0xca, 0xcf, 0xf9, 0x64, 0xe9, 0x67, 0xc9,
	0xd6, 0x2b, 0x9c, 0xdc, 0x84, 0x10, 0x1c, 0x24, 0xcb, 0xf4, 0x16, 0xa2, 0x33, 0x23, 0xae, 0x21,
	0xae, 0x1a, 0x8d, 0xef, 0xdc, 0x13, 0xda, 0xa1, 0x71, 0x11, 0x0d, 0xc6, 0xbe, 0x27, 0x4c, 0x6f,
	0x20, 0x76, 0xbb, 0x49, 0xf7, 0x42, 0x40, 0x40, 0x92, 0xeb, 0xf1, 0x93, 0x7d, 0xaf, 0x09, 0x60,
	0xe7, 0xda, 0xef, 0xbe, 0x4b, 0xb1, 0x02, 0x78, 0x25, 0x6d, 0xe4, 0x61, 0x80, 0xc4, 0xe5, 0xb9,
	0xdb, 0x58, 0x7d, 0x31, 0xfb, 0x33, 0x48, 0xf7, 0xa9, 0x97, 0xf9, 0x62, 0x05, 0xc9, 0x83, 0x6a,
	0x8d, 0xee, 0x18, 0x9f, 0x25, 0xd7, 0x8e, 0xd9, 0xe3, 0x0f, 0xff, 0x63, 0x9c, 0x61, 0x99, 0x4d,
	0xf4, 0x16, 0x4a, 0x6a, 0xee, 0x48, 0xa9, 0xd0, 0xde, 0xe7, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff,
	0xf5, 0x9c, 0x90, 0x95, 0x40, 0x01, 0x00, 0x00,
}
