// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: workflow.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type WorkflowRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowRequest) Reset()         { *m = WorkflowRequest{} }
func (m *WorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*WorkflowRequest) ProtoMessage()    {}
func (*WorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{0}
}
func (m *WorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowRequest.Unmarshal(m, b)
}
func (m *WorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowRequest.Marshal(b, m, deterministic)
}
func (m *WorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowRequest.Merge(m, src)
}
func (m *WorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_WorkflowRequest.Size(m)
}
func (m *WorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowRequest proto.InternalMessageInfo

func (m *WorkflowRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type WorkflowReply struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowReply) Reset()         { *m = WorkflowReply{} }
func (m *WorkflowReply) String() string { return proto.CompactTextString(m) }
func (*WorkflowReply) ProtoMessage()    {}
func (*WorkflowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{1}
}
func (m *WorkflowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowReply.Unmarshal(m, b)
}
func (m *WorkflowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowReply.Marshal(b, m, deterministic)
}
func (m *WorkflowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowReply.Merge(m, src)
}
func (m *WorkflowReply) XXX_Size() int {
	return xxx_messageInfo_WorkflowReply.Size(m)
}
func (m *WorkflowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowReply.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowReply proto.InternalMessageInfo

func (m *WorkflowReply) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type TriggerRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Flag                 string   `protobuf:"bytes,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Secret               string   `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Header               string   `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Body                 string   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	MessageId            int64    `protobuf:"varint,7,opt,name=messageId,proto3" json:"messageId,omitempty"`
	MessageText          string   `protobuf:"bytes,8,opt,name=messageText,proto3" json:"messageText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerRequest) Reset()         { *m = TriggerRequest{} }
func (m *TriggerRequest) String() string { return proto.CompactTextString(m) }
func (*TriggerRequest) ProtoMessage()    {}
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{2}
}
func (m *TriggerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerRequest.Unmarshal(m, b)
}
func (m *TriggerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerRequest.Marshal(b, m, deterministic)
}
func (m *TriggerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerRequest.Merge(m, src)
}
func (m *TriggerRequest) XXX_Size() int {
	return xxx_messageInfo_TriggerRequest.Size(m)
}
func (m *TriggerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerRequest proto.InternalMessageInfo

func (m *TriggerRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TriggerRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *TriggerRequest) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *TriggerRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *TriggerRequest) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *TriggerRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *TriggerRequest) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *TriggerRequest) GetMessageText() string {
	if m != nil {
		return m.MessageText
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkflowRequest)(nil), "pb.WorkflowRequest")
	proto.RegisterType((*WorkflowReply)(nil), "pb.WorkflowReply")
	proto.RegisterType((*TriggerRequest)(nil), "pb.TriggerRequest")
}

func init() { proto.RegisterFile("workflow.proto", fileDescriptor_892c7f566756b0be) }

var fileDescriptor_892c7f566756b0be = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x86, 0xbf, 0x6e, 0xfb, 0xea, 0x76, 0xc6, 0x2a, 0x46, 0x90, 0x30, 0xbc, 0x18, 0x13, 0x61,
	0x57, 0x13, 0x94, 0x09, 0x5e, 0xea, 0xae, 0xbc, 0xed, 0x06, 0x03, 0xef, 0x92, 0xf6, 0xac, 0x2b,
	0xad, 0x4d, 0x4c, 0x33, 0x66, 0xff, 0x8e, 0xbf, 0xc8, 0x9f, 0x24, 0x69, 0xa2, 0xdb, 0x64, 0x08,
	0xbb, 0x3b, 0xef, 0xc3, 0xfb, 0x1c, 0xc8, 0x21, 0x10, 0x6c, 0x84, 0xca, 0x96, 0xb9, 0xd8, 0x8c,
	0xa5, 0x12, 0x5a, 0x90, 0x86, 0xe4, 0x7d, 0xe0, 0xac, 0x44, 0x9b, 0x87, 0xd7, 0x70, 0xba, 0x70,
	0x8d, 0x10, 0xdf, 0xd6, 0x58, 0x6a, 0x42, 0xa0, 0xa5, 0xf1, 0x5d, 0x53, 0x6f, 0xe0, 0x8d, 0x3a,
	0x61, 0x3d, 0x0f, 0xaf, 0xa0, 0xb7, 0xad, 0xc9, 0xbc, 0x3a, 0x58, 0xfa, 0xf4, 0x20, 0x98, 0xab,
	0x34, 0x49, 0x50, 0xed, 0xee, 0xaa, 0x24, 0xfe, 0xd4, 0x2a, 0x89, 0x86, 0x65, 0x69, 0x11, 0xd3,
	0x86, 0x65, 0x66, 0x36, 0x6c, 0x99, 0xb3, 0x84, 0x36, 0x2d, 0x33, 0x33, 0xb9, 0x00, 0xbf, 0xc4,
	0x48, 0xa1, 0xa6, 0xad, 0x9a, 0xba, 0x64, 0xf8, 0x0a, 0x59, 0x8c, 0x8a, 0xfe, 0xb7, 0xdc, 0x26,
	0xb3, 0x83, 0x8b, 0xb8, 0xa2, 0xbe, 0xdd, 0x61, 0x66, 0x72, 0x09, 0x9d, 0x57, 0x2c, 0x4b, 0x96,
	0xe0, 0x73, 0x4c, 0x4f, 0x06, 0xde, 0xa8, 0x19, 0x6e, 0x01, 0x19, 0x40, 0xd7, 0x85, 0xb9, 0x79,
	0x4b, 0xbb, 0x16, 0x77, 0xd1, 0xed, 0x47, 0x03, 0xda, 0xdf, 0x0f, 0x27, 0x13, 0xe8, 0x84, 0xeb,
	0xe2, 0x31, 0xd2, 0xa9, 0x28, 0xc8, 0xf9, 0x58, 0xf2, 0xf1, 0xaf, 0xd3, 0xf5, 0xcf, 0xf6, 0xa1,
	0xcc, 0xab, 0xe1, 0x3f, 0xa7, 0xcd, 0x22, 0x95, 0x4a, 0x7d, 0x84, 0xf6, 0x00, 0xc1, 0x02, 0xf9,
	0x4a, 0x88, 0xcc, 0xdd, 0x94, 0x10, 0x53, 0xdb, 0x3f, 0xf0, 0x61, 0xf5, 0x1e, 0xba, 0x53, 0x25,
	0x8a, 0xa3, 0xbd, 0x09, 0xf4, 0xa6, 0x0a, 0x99, 0xc6, 0xbf, 0xcc, 0xc0, 0xb0, 0x99, 0x66, 0x1a,
	0x9d, 0xf6, 0xd4, 0x7e, 0xf1, 0x99, 0x4c, 0x6f, 0x24, 0xe7, 0x7e, 0xfd, 0xa9, 0xee, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x02, 0xca, 0x98, 0x1f, 0x76, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkflowClient is the client API for Workflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkflowClient interface {
	RunAction(ctx context.Context, in *WorkflowRequest, opts ...grpc.CallOption) (*WorkflowReply, error)
	RunScript(ctx context.Context, in *WorkflowRequest, opts ...grpc.CallOption) (*WorkflowReply, error)
	WebhookTrigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*WorkflowReply, error)
	CronTrigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*WorkflowReply, error)
	CreateTrigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*StateReply, error)
}

type workflowClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowClient(cc *grpc.ClientConn) WorkflowClient {
	return &workflowClient{cc}
}

func (c *workflowClient) RunAction(ctx context.Context, in *WorkflowRequest, opts ...grpc.CallOption) (*WorkflowReply, error) {
	out := new(WorkflowReply)
	err := c.cc.Invoke(ctx, "/pb.Workflow/RunAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) RunScript(ctx context.Context, in *WorkflowRequest, opts ...grpc.CallOption) (*WorkflowReply, error) {
	out := new(WorkflowReply)
	err := c.cc.Invoke(ctx, "/pb.Workflow/RunScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) WebhookTrigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*WorkflowReply, error) {
	out := new(WorkflowReply)
	err := c.cc.Invoke(ctx, "/pb.Workflow/WebhookTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) CronTrigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*WorkflowReply, error) {
	out := new(WorkflowReply)
	err := c.cc.Invoke(ctx, "/pb.Workflow/CronTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) CreateTrigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*StateReply, error) {
	out := new(StateReply)
	err := c.cc.Invoke(ctx, "/pb.Workflow/CreateTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServer is the server API for Workflow service.
type WorkflowServer interface {
	RunAction(context.Context, *WorkflowRequest) (*WorkflowReply, error)
	RunScript(context.Context, *WorkflowRequest) (*WorkflowReply, error)
	WebhookTrigger(context.Context, *TriggerRequest) (*WorkflowReply, error)
	CronTrigger(context.Context, *TriggerRequest) (*WorkflowReply, error)
	CreateTrigger(context.Context, *TriggerRequest) (*StateReply, error)
}

// UnimplementedWorkflowServer can be embedded to have forward compatible implementations.
type UnimplementedWorkflowServer struct {
}

func (*UnimplementedWorkflowServer) RunAction(ctx context.Context, req *WorkflowRequest) (*WorkflowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAction not implemented")
}
func (*UnimplementedWorkflowServer) RunScript(ctx context.Context, req *WorkflowRequest) (*WorkflowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunScript not implemented")
}
func (*UnimplementedWorkflowServer) WebhookTrigger(ctx context.Context, req *TriggerRequest) (*WorkflowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebhookTrigger not implemented")
}
func (*UnimplementedWorkflowServer) CronTrigger(ctx context.Context, req *TriggerRequest) (*WorkflowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CronTrigger not implemented")
}
func (*UnimplementedWorkflowServer) CreateTrigger(ctx context.Context, req *TriggerRequest) (*StateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrigger not implemented")
}

func RegisterWorkflowServer(s *grpc.Server, srv WorkflowServer) {
	s.RegisterService(&_Workflow_serviceDesc, srv)
}

func _Workflow_RunAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).RunAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workflow/RunAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).RunAction(ctx, req.(*WorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_RunScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).RunScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workflow/RunScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).RunScript(ctx, req.(*WorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_WebhookTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).WebhookTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workflow/WebhookTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).WebhookTrigger(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_CronTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).CronTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workflow/CronTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).CronTrigger(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_CreateTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).CreateTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workflow/CreateTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).CreateTrigger(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Workflow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Workflow",
	HandlerType: (*WorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunAction",
			Handler:    _Workflow_RunAction_Handler,
		},
		{
			MethodName: "RunScript",
			Handler:    _Workflow_RunScript_Handler,
		},
		{
			MethodName: "WebhookTrigger",
			Handler:    _Workflow_WebhookTrigger_Handler,
		},
		{
			MethodName: "CronTrigger",
			Handler:    _Workflow_CronTrigger_Handler,
		},
		{
			MethodName: "CreateTrigger",
			Handler:    _Workflow_CreateTrigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}
